### ISSUE TITLE
【经验/方案】使用中遇到了一些问题

### ISSUE THREAD

**Issue by xPlutow** [ske1996/matebook-13-2019-oc-efi#10]
- matebook13 2019
- i3
- 解锁CFG LOCK

HDMI连接显示器,电脑合盖,连接电源
短时间(半小时)睡眠后可以唤醒
长时间(2.5小时)睡眠后键盘鼠标亮,但是两个显示器都不亮.

**Comment by ske1996** [comment]
笔记本的HDMI合盖这个问题，我确实不是怎么解决，而且确实看到了除了matebook13之外的机型也有这个问题，包括白果，所以这个可能属于纯粹的macos的bug

**Comment by xPlutow** [comment]
好的知道了. 谢谢

**Comment by ske1996** [comment]
如果你不怕影响使用的话，
你可以禁用合盖睡眠
