### ISSUE TITLE
matebook13 2020 amd R5 3500u款能用吗

### ISSUE THREAD

**Issue by zhangdongdongzdd** [ske1996/matebook-13-2019-oc-efi#100]
*BEFORE YOU REPORT A BUG,ENSURE YOU DID READ ALL ISSUE OF MY REPO.  (casue maybe there was someone had reported same problem and i replied him/her)    
⚠️If you dont follow those option under this page when you report a issue,i will delete it without any notice

*请确定你在提交issue去报告一个bug前，你有认真读过我写的所有注意事项，并且读过这个项目里所有issue（因为可能已经有人提交过一样的了）
⚠️不按以下格式提交的一律删除处理

**Device info（设备信息）**

Matebook xx 20xx  

CPU:  
RAM:  
SSD:
MacOS version:   
EFI version:

**Describe the bug（问题简述）**

**To Reproduce（详述问题发生前的操作）**

**Screenshots（截图）**

**Additional context（其他附件事项）**

**Comment by ske1996** [comment]
我有写仅intel ver

**Comment by zhangdongdongzdd** [comment]
> 我有写仅intel ver
额
