### ISSUE TITLE
【待解决】matebook13-18版i7版本--按照教程修改dvmt至64mb的时候，右侧Type-C只能4k30hz。

### ISSUE THREAD

**Issue by rebuqi** [ske1996/matebook-13-2019-oc-efi#101]
如题。请教大佬解决方法
已修改bios和分区中的config.plist文件，用本子右侧Type-C只能4k30hz，不知道是否还需要别的配置

**Comment by ske1996** [comment]
你确定都改对的话，就检查一下你的线材还有屏幕支持问题吧

**Comment by rebuqi** [comment]
我win10下是可以4k60hz的，说明线材和显示器是支持的，可能还是配置的问题。

**Comment by ske1996** [comment]
那行，我没4k的设备去测试，你检查一下是否都是绝对改的跟我一样了。因为有时候保存不一定生效

如果你解决了，麻烦告诉我一下方法，谢谢

**Comment by ske1996** [comment]
我给的东西也是理论性质的

**Comment by ske1996** [comment]
或者你试试把缓冲帧打成655，我这个打得是630

**Comment by rebuqi** [comment]
655应该打成多少？

**Comment by ske1996** [comment]
Google is your friend
