### ISSUE TITLE
matebook-13 message无法登陆 请帮忙看一下，里面有图

### ISSUE THREAD

**Issue by 1245040330** [ske1996/matebook-13-2019-oc-efi#103]
*BEFORE YOU REPORT A BUG,ENSURE YOU DID READ ALL ISSUE OF MY REPO.  (casue maybe there was someone had reported same problem and i replied him/her)    
⚠️If you dont follow those option under this page when you report a issue,i will delete it without any notice

*请确定你在提交issue去报告一个bug前，你有认真读过我写的所有注意事项，并且读过这个项目里所有issue（因为可能已经有人提交过一样的了）
⚠️不按以下格式提交的一律删除处理

**Device info（设备信息）**

Matebook 13 2018  

CPU:  8565u
RAM:  8G
SSD:512
MacOS version:   Big Sur 正式版 黑果小兵镜像
EFI version:github 11.13号的oc

**Describe the bug（问题简述）**
matebook-13 message无法登陆 
**To Reproduce（详述问题发生前的操作）**
输入账号密码过几秒又重新出现登陆窗口

**Screenshots（截图）**

[屏幕录制2020-11-14 上午7.52.49.zip](https://github.com/ske1996/matebook-13-2019-oc-efi/files/5539818/2020-11-14.7.52.49.zip)

**Additional context（其他附件事项）**

**Comment by 1245040330** [comment]
压缩包里有操作视频 oc是该项目里的最新oc。三码已经注入  生成之后在苹果官网检查无效之后保存的

**Comment by ske1996** [comment]
applestore跟icloud情况如何？可以登陆吗

还有就是你这个是新装的吗，之前有装过黑苹果吗

有改config里的uuid吗

装好以后改三码前登过appleid吗

**Comment by 1245040330** [comment]
app store跟iCloude 可以登陆
新装的。之前也装过黑苹果
改过config 的uuid 
改三码前登过appleid

**Comment by ske1996** [comment]
> app store跟iCloude 可以登陆
> 
> 新装的。之前也装过黑苹果
> 
> 改过config 的uuid 
> 
> 改三码前登过appleid
> 
> 



猜测跟你改三码前登录appleid有关

电脑退出appleid
在手机上登录appleid，删除掉里面的这个黑苹果的macbookpro设备
重新定制一套uuid,mlb,ssn,rom
全套新的
然后关机，清空nvram
再开机，检查好一定确定改好了，然后再登录一下试试

**Comment by 1245040330** [comment]
三码 自动生成好之后 去苹果官网检测无效之后保存是吧

**Comment by 1245040330** [comment]
还是不行。  目前问题 message  FaceTime 随航 隔空投 等都有问题

**Comment by ske1996** [comment]
无线随航和隔空投送我说过不可用

你的那个就是三码与appleid的事，我看不到你做了什么，但是简单来说就是退id，icloud删设备，改三码，reset nvram，这样解决
