### ISSUE TITLE
18款matebook 14，睡眠后唤醒屏幕一直是没有显示的，但是屏幕背光已经亮了

### ISSUE THREAD

**Issue by Tony-debug-777** [ske1996/matebook-13-2019-oc-efi#108]
Matebook 14 2018
CPU:i5-8265u
RAM:8G
SSD:西数硬盘
版本 Catalina 10.15.4

**Comment by ske1996** [comment]
次次都出现吗？

开启hidpi了吗，尤其是第一步注入edid的，选了吗

**Comment by Tony-debug-777** [comment]
开了hidpi也注入了edid，用的别人的：https://github.com/xzhih/one-key-hidpi/blob/master/README-zh.md，还是不得行。

**Comment by ske1996** [comment]
所以次次都出现吗

**Comment by Tony-debug-777** [comment]
对，每次都是一样，关了hidpi也是一样。我重新刷一下系统试试。用的是黑果小兵的10.15.4

**Comment by ske1996** [comment]
因为看不到你具体做了什么，我觉得你是有哪里没做对，所以你从头严丝合缝的再来一遍

一般来说唤醒黑屏就是缓冲帧，usb，edid的问题，不过都可以排除，因为很多人都装了，也没有出现。

唤醒黑屏的解决办法一半都可以通过注入edid来解决

我觉得你是有哪里没做对，所以你从头严丝合缝的再来一遍

**Comment by Tony-debug-777** [comment]
好的，我再试试。感谢回复

**Comment by ske1996** [comment]
想起一些东西，解锁cfg后，设置/节能中的电源or电池里的硬盘睡眠不要勾选，电源小憩不压迫勾选，网络唤醒不要勾选，设置/蓝牙中的高级➡️蓝牙唤醒不要勾选

然后终端运行：

'''
sudo pmset -a hibernatemode 0
sudo rm -rf /private/var/vm/sleepimage
sudo touch /private/var/vm/sleepimage
sudo chflags uchg /private/var/vm/sleepimage
sudo pmset -a standby 0
sudo pmset -a autopoweroff 0
sudo pmset -a powernap 0
sudo pmset -a proximitywake 0
sudo pmset -b tcpkeepalive 0
'''

**Comment by Tony-debug-777** [comment]
试了，还是不行。我试下外接显示器。感谢大佬

**Comment by NCVT2002010008** [comment]
大佬，你好。现在我也出现这种问题了。目前系统是13.2.1。
