### ISSUE TITLE
Matebook14 CFG lock

### ISSUE THREAD

**Issue by Slight123** [ske1996/matebook-13-2019-oc-efi#109]
Matebook 14 2019 

CPU:  I5 8265u
RAM:  8G
SSD:512G
MacOS version:   
EFI version:

**Describe the bug（问题简述）**
我看CFG解锁部分，要先升级bios到1.28版本，我的还在1.06版本，电脑管家里也没有更新，官网上也没有找到相关更新，请问我该怎么升级bios，或者是否可以在现版本进行后续操作？

**Comment by GJTNB** [comment]
我也是，找不到bios，我直接改的

**Comment by ske1996** [comment]
直接去改吧

我也是为了保守起见那么写的而已
