### ISSUE TITLE
【经验/方案】关于CFG解锁的问题

### ISSUE THREAD

**Issue by jiaogger** [ske1996/matebook-13-2019-oc-efi#11]
我按照博主的方法尝试了解锁cfg,想请教一下是不是0030 000e对应的数字是0就解锁成功了？

**Comment by jiaogger** [comment]
![Uploading IMG_1933.jpeg…]()

**Comment by ske1996** [comment]
说起来是的，但是有可能在RU(你解锁cfg的那个红红蓝蓝的界面)里面没有保存成功

所以，你去下载一个hackintool，这个是macos里面的软件，用这个软件可以检测你有没有成功解锁，具体点软件的哪里，你去百度搜索"hackintool 解锁cfg"

**Comment by jiaogger** [comment]
> 说起来是的，但是有可能在RU(你解锁cfg的那个红红蓝蓝的界面)里面没有保存成功
> 
> 所以，你去下载一个hackintool，这个是macos里面的软件，用这个软件可以检测你有没有成功解锁，具体点软件的哪里，你去百度搜索"hackintool 解锁cfg"

好的，感谢博主

**Comment by ske1996** [comment]
把这个重新打开吧，别close了，这个也是个经验，让别人看到了，能帮助他们，我非要所有人都提交issue就是为了让更多的人看到经验

**Comment by jiaogger** [comment]
> 把这个重新打开吧，别close了，这个也是个经验，让别人看到了，能帮助他们，我非要所有人都提交issue就是为了让更多的人看到经验

好的好的，手滑了一下下～

**Comment by jiaogger** [comment]
已经解决了，严格按照楼主教程执行就好，完成更改后用hackintool自查一下 00E2参数下那个cfg lock置0就ok了
