### ISSUE TITLE
matebook14 2020  HDMI不可用

### ISSUE THREAD

**Issue by dongqianggo** [ske1996/matebook-13-2019-oc-efi#110]
Matebook 14 2020
CPU:i5-10210U
RAM:16G
SSD:西数硬盘

按照efi,oc引导

Doesnt work: 蓝牙和HDMI不可用，触摸板和WiFi有时好有时坏

请教下样修改文件可以让hdm有信号

**Comment by ske1996** [comment]
OS版本和efi版本号没写，下次这样的直接就删除issue

尝试重置nvram

你说的这个问题我不理解为什么
因为我经过测试了，都正常

**Comment by dongqianggo** [comment]
对不起，我是小白！


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: ske1996 <notifications@github.com&gt;
发送时间: 2020年11月18日 19:31
收件人: ske1996/matebook-13-2019-oc-efi <matebook-13-2019-oc-efi@noreply.github.com&gt;
抄送: dong <1012082932@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ske1996/matebook-13-2019-oc-efi] matebook14 2020  HDMI不可用 (#110)





 
OS版本和efi版本号没写，下次这样的直接就删除issue
 
尝试重置nvram
 
你说的这个问题我不理解为什么
 因为我经过测试了，都正常

**Comment by ske1996** [comment]
所以你倒是告诉我啊，你用的哪个efi版本号是什么，系统版本是什么

我在issue的格式里写了啊
Os version
Efi version
这跟小白有啥关系
