### ISSUE TITLE
【已解决】matebook13 2019 安装好Big Sur 后没有音频

### ISSUE THREAD

**Issue by liutao-hue** [ske1996/matebook-13-2019-oc-efi#114]
使用matebook13 2019 Big Sur 安装好Big Sur 后没有音频设备被识别出来，请问该怎么解决
![image](https://user-images.githubusercontent.com/75152458/100493319-d552be80-3170-11eb-8a5f-ba0b98b89be3.png)

**Comment by ske1996** [comment]
咱们机器一样啊，不应该啊

在那个boot-args里添加alcid＝21

**Comment by liutao-hue** [comment]
怎么加，我这样加对吗
<key>boot-args</key>
<string>-v debug=0x100 keepsyms=1 alcid=21</string>

**Comment by liutao-hue** [comment]
怎么加，我这样加对吗
<key>boot-args</key>				
<string>-v debug=0x100 keepsyms=1 alcid=21</string>

**Comment by ske1996** [comment]
> 怎么加，我这样加对吗
> boot-args
> -v debug=0x100 keepsyms=1 alcid=21

对啊，还是没声是吗？

reset一下nvram
