### ISSUE TITLE
其他都弄好了 电脑型号是matebook14 2019款 就出现一个小问题

### ISSUE THREAD

**Issue by Fance-rest** [ske1996/matebook-13-2019-oc-efi#116]
解锁cfg的时候第一步是将bios驱动升级至1.28 可以是我现在的版本不是，只有1.06，使用官方的电脑助手显示已是最新版本，到官网上也没有找到任何下载链接，在咨询了客服之后被告知没有最新的，现在很犹豫是不是可以直接使用当前版本的bios

**Comment by ske1996** [comment]
是
