### ISSUE TITLE
【solved】 issue about you cant boot bigsur，关于引导bigsur报错

### ISSUE THREAD

**Issue by battall** [ske1996/matebook-13-2019-oc-efi#117]
i was using big sur kext without any change, it was working great until today, my laptop crashed (i closed firefox then it freeze, so i shut down holding power button)

it does not boot now, i reintalled big sur from recovery (after reinstall it booted just one time, after reboot same error exists), tried to update kexts but nothing changed, i think it is because of 
"busy timeout [0,1,2,3] (60s) macbookpro15,2"  but i don't know really. 

![IMG_20201211_101323_686.jpg](https://user-images.githubusercontent.com/50958739/101913949-bfafb100-3bd4-11eb-9047-175e53e98ea7.jpg)

**Comment by ske1996** [comment]
Related to sip option
Edit config.plist with propertree 
Change nvram/7c....../csr-active-config to 00000000
Save and reinstall

**Comment by battall** [comment]
wow it really did the job... thank you so much!

**Comment by ske1996** [comment]
If you dont mind,i wanna reopen this issue for make feedback of issue to a guide book or something same as it.
The feedback of all issue likes some experience which can help some people who has some problem with their hackintosh
