### ISSUE TITLE
关于引导bigsur报错

### ISSUE THREAD

**Issue by DylanYU0526** [ske1996/matebook-13-2019-oc-efi#118]
**Device info（设备信息）**

Matebook 14 2019

CPU:  i5-8265U CPU
RAM:  8.0GB
SSD:WDC PC SN720 SDAPNTW-512G-1127 (512GB)
MacOS version:   macOS BigSur 11.0.1 20B50 正式版 with Clover 5126原版镜像[双EFI版][UEFI and MBR]
EFI version: Matebook.13.14.2018-2019.BigSur.1113.7z

**Describe the bug（问题简述）**
安装bigsur报错，apfs_get_firmlink_target_vnode:2007:vnode_lookup(Library)failde with error 2 AFI:Denying coure dump for pid 961 (logd)Process[961] crashed:logd. Too many corpses being created

**To Reproduce（详述问题发生前的操作）**
1. 按照视频操作至clover，安装bigsur
2. 电脑重启至clover，选择新出现的盘图标，安装mac
3. 第二次重启，依然选择新出现的盘图标
4. 发生报错
5.看到黑果小兵下面回复说按F3 找到Preboot 但是并没有找到

**Screenshots（截图）**
![微信图片_20201215102901](https://user-images.githubusercontent.com/76023157/102160419-5f648c00-3ec0-11eb-8787-efcdf126aa92.jpg)
![image](https://user-images.githubusercontent.com/76023157/102160486-81f6a500-3ec0-11eb-84ce-a5f0ce102d45.png)

***链接******

https://github.com/daliansky/daliansky.github.io/issues/231

请帮忙看一下谢谢~

**Comment by ske1996** [comment]
![image](https://user-images.githubusercontent.com/63181546/102166576-b9b91900-3ecf-11eb-9dd6-3a83d6d84191.jpeg)

我说了，要安装bigsur，去找oc的教程，使用oc的efi

我的那个clover的没做bigsur的support
