### ISSUE TITLE
oc：failed to load configuration ota升级big sur报错

### ISSUE THREAD

**Issue by 648483044** [ske1996/matebook-13-2019-oc-efi#119]
*BEFORE YOU REPORT A BUG,ENSURE YOU DID READ ALL ISSUE OF MY REPO.  (casue maybe there was someone had reported same problem and i replied him/her)    
⚠️If you dont follow those option under this page when you report a issue,i will delete it without any notice

*请确定你在提交issue去报告一个bug前，你有认真读过我写的所有注意事项，并且读过这个项目里所有issue（因为可能已经有人提交过一样的了）
⚠️不按以下格式提交的一律删除处理

**Device info（设备信息）**

Matebook 13 2018

CPU:  i5-8265u
RAM:  8g
SSD:西数
MacOS version:   bigsur11.x
EFI version:Catalina删除替换为bigsur

ota升级已解锁cfg，替换oc后启动失败。

**Comment by ske1996** [comment]
图呢？日志呢？你的操作的详细描述呢？你怎么换的？直接拖进去替换的还是先删除旧的然后再复制新的进去？

**Comment by 648483044** [comment]
> 图呢？日志呢？你的操作的详细描述呢？你怎么换的？直接拖进去替换的还是先删除旧的然后再复制新的进去？

删除后复制进入的。

**Comment by ske1996** [comment]
你的引导日志给我看看

**Comment by 648483044** [comment]
> 你的引导日志给我看看

引导界面是苹果进度显示不出来

**Comment by ske1996** [comment]
https://dortania.github.io/OpenCore-Install-Guide/

根据这个教程开启调试模式，保存日志后，日志给我看一下，你的那个没亲眼看到，我只能看日志

**Comment by ske1996** [comment]
要么就是config损坏，要么就是config丢失，很多东西没看到我不太好说为什么

**Comment by 648483044** [comment]
> https://dortania.github.io/OpenCore-Install-Guide/
> 
> 根据这个教程开启调试模式，保存日志后，日志给我看一下，你的那个没亲眼看到，我只能看日志

好的，多谢🙏

**Comment by 648483044** [comment]
> 要么就是config损坏，要么就是config丢失，很多东西没看到我不太好说为什么

![Uploading 6E4AE4EC-D50D-43F9-AAFF-AED11700EA3F.jpeg…]()

**Comment by ske1996** [comment]
你的图片挂了。。。。而且日志应该是保存的txt格式的，是efi给你自动保存的，我给你的教程你应该没有仔细看

**Comment by ske1996** [comment]
![1811608874837_ pic_hd](https://user-images.githubusercontent.com/63181546/103121366-2b0e7e00-46bf-11eb-8d3d-ae19a3a6ee52.jpg)


你去群里找其他人帮你仔细看看吧，最近我比较忙
