### ISSUE TITLE
Matebook14 2020 i5  catalina  10.15.5  oc引导   0926.efi cfg已解锁 蓝牙不可用 wifi搜索不到网络 

### ISSUE THREAD

**Issue by 1925273943** [ske1996/matebook-13-2019-oc-efi#120]
Matebook 14 2020
CPU: i5
RAM: 16
SSD: KXG50ZNV512G 东芝
Macos Version：catalina  10.15.5
EFI Version:  matebook14 2020 catalina 0926.efi

Works fine:  
    睡眠唤醒正常
   偶尔唤醒会闪一下并且花屏一下
   触摸板正常
   键盘快捷键正常
   耳机接口可用
    睡眠可使用
   hdmi 没测试  
   cup变频没测试
   会有开机跑码后进入不到系统错误
   续航略快

Doesnt work:
     摄像头  
     蓝牙
     _wifi能打开 但是搜索不到网络  可以使用iphone共享网络_  更正  reset一下nvram  之后可以使用wifi搜索到网络了

    bios 1.19  日期是6月11日的 解锁cfg跟着文档来就行了  

![IMG_1034](https://user-images.githubusercontent.com/52321873/103127477-eee21a00-46cc-11eb-80d6-ba55f0427a68.JPG)
![IMG_1035](https://user-images.githubusercontent.com/52321873/103127481-f275a100-46cc-11eb-9b8c-b21b6c362643.JPG)
![IMG_1036](https://user-images.githubusercontent.com/52321873/103127484-f5709180-46cc-11eb-8748-86d260a321fc.JPG)
![IMG_1037](https://user-images.githubusercontent.com/52321873/103127522-15a05080-46cd-11eb-8b02-8319f662ac6d.JPG)

**Comment by ske1996** [comment]
拍一下设置的主界面的截图

**Comment by 1925273943** [comment]
> 拍一下设置的主界面的截图
![DF3B6861-5682-4C91-8A9A-30CF70BA73AA](https://user-images.githubusercontent.com/52321873/103150514-ef071600-47af-11eb-82df-eea37a785fce.jpeg)
而且WiFi重启后依然搜索不到网络  仍需手动reset nvram

**Comment by ske1996** [comment]
我是想看你蓝牙，拍"设置"的截图，"设置"的主界面的截图。不要进什么里面的分项

**Comment by ske1996** [comment]
Wifi这个按理说不应该，你试试去我给的出的wifi驱动作者的地址里更新一下最新的驱动，或者把oc/kexts/airportitlwm给删了，换成itlwm之后，安装heliport那个app，上述的东西都在wifi驱动作者的主页里可以分别在不同project里面找到
