### ISSUE TITLE
19年matebook14已经安装好正常使用，只是引导win的时候直接蓝屏。

### ISSUE THREAD

**Issue by dayn97** [ske1996/matebook-13-2019-oc-efi#124]
19年matebook14已经安装好正常使用，只是引导win的时候直接蓝屏。
不知道怎么解决。

**Comment by dayn97** [comment]
![Uploading photo_2021-01-20_21-46-17.jpg…]()

**Comment by ske1996** [comment]
去仔细阅读安装后中的注意事项
