### ISSUE TITLE
怎么才能正常使用隔空投送 facetime这些功能

### ISSUE THREAD

**Issue by 1070548197** [ske1996/matebook-13-2019-oc-efi#125]
**Device info（设备信息）**

Matebook 13 2019 

CPU:  i5 8xxx
RAM:  8gb
SSD: 512
MacOS version:   11.1
EFI version: 不知道

**Describe the bug（问题简述）**
三码也搞了 但是还是不行
**To Reproduce（详述问题发生前的操作）**
所有的都正常了 只有隔空投送这问题了

**Comment by ske1996** [comment]
目前无解，找我没用，去仔细关注我给出的wifi驱动的项目
