### ISSUE TITLE
首先谢谢大佬的efi，想问问wifi的速度能提升吗？

### ISSUE THREAD

**Issue by dayn97** [ske1996/matebook-13-2019-oc-efi#126]
用大佬的EFI,所有的功能正常，除了hdmi，之前弄过一次，黑屏了，后面重装干脆不弄了。现在除了摄像头，显卡好像都正常使用。就是wifi测速才30来m，不知道能不能提升一些。

**Comment by dayn97** [comment]
![Uploading 9BFF38A6-5562-4EA2-8310-793B2A995174.png…]()

**Comment by ske1996** [comment]
未按格式提交，截图挂了，重新创建issue
