### ISSUE TITLE
感谢大佬的efi,正常使用，就是wifi速度只有30m的样子

### ISSUE THREAD

**Issue by dayn97** [ske1996/matebook-13-2019-oc-efi#127]
感谢老大提供的efi，现在功能都算正常使用，除了说明的摄像头和独显不能用，还有一小点问题，就是Wi-Fi下测速只有30m，切换到win10测速有300左右，宽带300m移动宽带。不知是否有解决办法。

Matebook 14 2019
CPU: 2.1 GHz 四核Intel Core i5
RAM:8 GB 2133 MHz LPDDR3
SSD:WDC PC SN730 SDBPNTY-512G-1027
wifi：
软件版本：
  CoreWLAN：	13.0 ((null))
  CoreWLANKit：	13.0 ((null))
  附加菜单：	13.0 ((null))
  系统信息：	12.0 (1500)
  IO80211系列：	12.0 (1200.12.2b1)
  诊断：	1.0 (910)
  AirPort实用工具：	未安装
  接口：
en1：
  卡类型：	AirPort Extreme  (0x8086, 0x2034)
  固件版本：	itlwm: 1.1.0 fw: 48.1335886879.0
  MAC地址：	98:af:65:c6:fa:02
  位置：	FCC
  国家/地区代码：	ZZ
  支持的PHY模式：	802.11 a/b/g/n/ac
  支持的频段：	1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 149, 153, 157, 161, 165
  无线网络唤醒：	支持
  隔空投送：	支持
  “隔空投送”频段：	0
  状态：	已连接
  当前网络信息：
mrli_5G：
  PHY模式：	802.11n
  BSSID：	54:48:e6:ad:dc:df
  频段：	157
  国家/地区代码：	ZZ
  网络类型：	基础结构
  安全性：	WPA/WPA2个人级
  信号/噪声：	-67 dBm / -127 dBm
  传输速率：	140
  MCS索引：	15
Macos Version：catalina 10.15.7
EFI Version:Matebook.13.14.2018-2019.Catalina.0926.7z
Works fine:

Doesnt work:

**Comment by dayn97** [comment]
![1](https://user-images.githubusercontent.com/47072414/105932238-96b18580-6087-11eb-9878-05b79f8b5dac.jpg)

**Comment by ske1996** [comment]
Hdmi的那个不知道是不是你，你去点开我的正常使用功能中的hdmi，点一下那个展开，里面有详细解决办法，你去按照planb修改一下你自己的config的缓冲帧就好

Wifi问题去点击可正常使用中wifi的那部分，点击展开有wifi驱动作者的信息，去他的主页下载最新的wifi驱动替换即可
