### ISSUE TITLE
Matebook B5-420 macOS Big Sur完美 但是OC无法引导Windows 10

### ISSUE THREAD

**Issue by P4t4r-W0ng** [ske1996/matebook-13-2019-oc-efi#128]
配置：i7-10510U
显卡：UHD620
当用OC引导Windows时出现错误 一直重启
代码：ACPI BIOS ERROR
禁用OC 直接Windows Boot Manager启动 Windows可正常进入系统
感谢作者大大awa

**Comment by ske1996** [comment]
在安装后的部分我写了不要用oc引导windows
你会报错也是我故意弄得

**Comment by ske1996** [comment]
你直接用easyuefi给原生的uefi bootloader创建一个windows的窗口就行，我贴出来的教程视频里有
