### ISSUE TITLE
Got a Trackpad issue by touchscreen ver MB13 2019(sales in Poland)

### ISSUE THREAD

**Issue by tosziro** [ske1996/matebook-13-2019-oc-efi#129]
Matebook 13 2019 i7 with MX150 and Touchscreen

Im starting macOS recovery (big sur) and I cant even start installation because after some time trackpad and touch screen stop to work. Tried five times and its like that every time. Please help me guys.

**Comment by ske1996** [comment]
Try to install Macos with an USB external mouse

If you got trackpad issue again after you enter the os,let me know

**Comment by ske1996** [comment]
And please use the "bug report" option and write your device's detailed info when you report a issue

**Comment by ske1996** [comment]
Btw,i think you can try EFI for mb13 2020ver

My EFI floder creat by China area sales version MateBook,the touch screen version is 2020ver in China

**Comment by tosziro** [comment]
Thank you for respond. I installed succesfully big sur as sugested using mouse but touchpad problem still exits after installation.
When I try EFI for Matebook 13 2020 it results in not working toouchpad even for a second.

My device is : Huawei MateBook 13 i7-8565U with Touch screen
NVIDIA GeForce MX150/Intel UHD Graphics 620
WDC PC SN720 SDAPNTW-512G-1027
8GB RAM

**Comment by ske1996** [comment]
okay,maybe there are some different hardware between the sales area.
the trackpad works well in my test whatever 2019 or 2020ver.
but my device are all bought in China.
send your dsdt here,so i can make a ssdt for trackpad.
google how to extract dsdt by yourself.

btw,where are you living?
i mean i want to know the sales area of your matebook

**Comment by tosziro** [comment]
Thank you. Attached DSDT taken on Linux with SSDTTime. Hope this is fine. I'm living and bought this laptop in Poland.
[DSDT.zip](https://github.com/ske1996/matebook-13-2019-oc-efi/files/5926218/DSDT.zip)

**Comment by ske1996** [comment]
btw,did you try to run "sudo kextcache -i\" in terminal?
[アーカイブ.zip](https://github.com/ske1996/matebook-13-2019-oc-efi/files/5926389/default.zip)
here are 3 new ssdt made from your dsdt.
replace the ssdt-xosi to new one,and patch(enable) the ssdt-gpi0 and ssdt-tpd0 in config.plist

then reboot

let me know the result

**Comment by tosziro** [comment]
Sadly no change, again it stop to work after around one minute. :/
I found that on Matebook X people have similar issue and they resolved it by turning off touch screen. Do you know maybe how to turn it off on Matebook 13?

https://github.com/profzei/Matebook-X-Pro-2018/issues/46

And yes, i tried sudo kextcache -i but no result.

**Comment by ske1996** [comment]
i am not sure if it related to touchscreen,because the matebook 14 2020 which is sales in China with a touchable screen,and i didnt ban that in ssdt and it works well.

here is a guide about i2c gpio trackpad,and told a way to disable touchscreen,because i dont have the device same as yours and it is alittle complicated,so you need do it by yourself.
but it was written in Chinese,so maybe you need to read it with google tranlate in chrome. 

http://yqp7js.coding-pages.com/2020/05/17/%E7%94%A8%E7%83%AD%E8%A1%A5%E4%B8%81%E4%BF%AE%E7%90%86%E4%BD%A0%E7%9A%84%E8%A7%A6%E6%91%B8%E6%9D%BF%EF%BC%88TouchPad-Hotpatch%EF%BC%89/

**Comment by ske1996** [comment]
btw,a hint for you:

the touchable screen in MateBook is an I2C HID device, same as trackpad.

**Comment by tosziro** [comment]
I found EFI that I used some time ago on this laptop and trackpad works fine now with touch screen enabled. Dont know sadly what is the diference since this EFI as I remeber is based on yours, I only updated opencore to latest and kexts. The only issue I have right now is kinda high temperatures, around 44 degrees on idle.

**Comment by ske1996** [comment]
I deleted the ssdt for trackpad since 20200816，maybe this is related to what you said.

**Comment by ske1996** [comment]
Btw,i think 44 °C is not high……same as mine

**Comment by tosziro** [comment]
I today used your latest EFI for Matebook 13 2019 and had again this issue. But then I updated kext Voodool2C and VooDooPS2Controller to latest and problem is gone. So this is some issue with older kext versions.

**Comment by ske1996** [comment]
Okay,Got it,thank you for let mw know that
