### ISSUE TITLE
matebook13 2019更新WhateverGreen后开机黑屏

### ISSUE THREAD

**Issue by wrb2012** [ske1996/matebook-13-2019-oc-efi#132]
查看更新日志后已找到解决办法：
Boot argument 加入-igfxblr；并且device property里显卡注入中开启enable-backlight-registers-fix
<img width="950" alt="image" src="https://user-images.githubusercontent.com/13612969/107502276-6dd6d780-6bd3-11eb-8cfe-bc0a80b82105.png">

**Comment by ske1996** [comment]
😂😂谢谢你的report，这个我之前就知道了……其实lilu还有whatevergreen这样的驱动，如果用着没毛病就不要更新了……
