### ISSUE TITLE
matabook14 2020 i5 mx250 big11.2基本完美

### ISSUE THREAD

**Issue by Hongfumal** [ske1996/matebook-13-2019-oc-efi#133]
Matebook 14 2020  
CPU:i5 10代
RAM: 16G
SSD: SN750 黑盘
Macos Version：big11.2.1
EFI Version: 20210130
bios：1.19

Works fine: 
1、触控板，各种手势正常使用
2、cfg解锁正常，地址还是0x3E
3、蓝牙热启动正常
4、无线，有时开机后不能识别，再次重启后正常，间歇性问题，没有找到原因

Doesnt work:
1、type-c接口，使用扩展坞，外接显示器无法识别

**Comment by Hongfumal** [comment]
非常感谢ske1996辛勤细致的工作，也希望可以尝试为该项目贡献些力量。大家共同维护。再次感谢ske1996！！！！🙏🙏

**Comment by ske1996** [comment]
缓冲帧只针对hdmi的接口直接输出，不对typec转接工作

**Comment by ske1996** [comment]
Wifi问题为从windows切换至macos导致

**Comment by Hongfumal** [comment]
针对type-c这个转接问题，您有没有好的解决思路？或者您在这方面有没有好的解决方案，有兴趣先尝试一下。非常感您对matebook系列做出的贡献，thank you

**Comment by ske1996** [comment]
Hdmi详细说明里面的planb，用那个就行了

**Comment by ske1996** [comment]
对了🤩🤩🤩看到你说你想帮帮忙，我这有两个东西让我蛋疼了一段时间，有没有兴趣研究一下？

1. 摄像头:摄像头部分能用部分不能用，这个问题是华为的采购不同厂商摄像头导致的，但是uvc协议是通用的，加上10年前华硕的机子的黑苹果就有过类似的事，通过仿冒来解决，因此猜测是可能有个厂商白名单，但是我们仿冒过了也无效，所以你有没有兴趣帮忙找找办法能更改硬件vid以及pid的？

2. 15w功耗限制以及最优变频以及耗电问题，这个属于一个不可完美三角，上述三个问题单独解决都很简单，但是同时兼顾就工程量很大，15w功耗限制我觉得可以给它去了，因为i7-8565这个u最大可以给到25w的tdp，应该能通过改pl1和pl2就轻松解决(比如瞬时boost最高25w，长期boost最高18w这样)，然后，变频这个最麻烦，因为变频幅度与耗电成正比例，运行频率的大小也与耗电成正比例，最低设得太小最高设的太大会反而更费电，我是希望能找个平衡三者的最优解，但是我比较懒🤣🤣🤣你有兴趣找吗

**Comment by seils1984** [comment]
> Matebook 14 2020
> CPU:i5 10代
> RAM: 16G
> SSD: SN750 黑盘
> Macos Version：big11.2.1
> EFI Version: 20210130
> bios：1.19
> 
> Works fine:
> 1、触控板，各种手势正常使用
> 2、cfg解锁正常，地址还是0x3E
> 3、蓝牙热启动正常
> 4、无线，有时开机后不能识别，再次重启后正常，间歇性问题，没有找到原因
> 
> Doesnt work:
> 1、type-c接口，使用扩展坞，外接显示器无法识别

我和你一样的配置。想请问下 你有没有试过外接4k显示器。
我改了dvmt 64m后会花屏，但是外接4k显示器始终开不了hidpi。之前以为开了，但是后来发现都不是hidpi。只是有了比较高的分辨率，而且还模糊。

**Comment by ske1996** [comment]
> > Matebook 14 2020
> 
> > CPU:i5 10代
> 
> > RAM: 16G
> 
> > SSD: SN750 黑盘
> 
> > Macos Version：big11.2.1
> 
> > EFI Version: 20210130
> 
> > bios：1.19
> 
> > 
> 
> > Works fine:
> 
> > 1、触控板，各种手势正常使用
> 
> > 2、cfg解锁正常，地址还是0x3E
> 
> > 3、蓝牙热启动正常
> 
> > 4、无线，有时开机后不能识别，再次重启后正常，间歇性问题，没有找到原因
> 
> > 
> 
> > Doesnt work:
> 
> > 1、type-c接口，使用扩展坞，外接显示器无法识别
> 
> 
> 
> 我和你一样的配置。想请问下 你有没有试过外接4k显示器。
> 
> 我改了dvmt 64m后会花屏，但是外接4k显示器始终开不了hidpi。之前以为开了，但是后来发现都不是hidpi。只是有了比较高的分辨率，而且还模糊。

你所描述出的问题，都给个视频看看，电脑端可以直接拖视频到这个里面的对话框上传
Btw,你缓冲帧改了吗，就是对应64m dmvt的

**Comment by Hongfumal** [comment]
> > Matebook 14 2020
> > CPU:i5 10代
> > RAM: 16G
> > SSD: SN750 黑盘
> > Macos Version：big11.2.1
> > EFI Version: 20210130
> > bios：1.19
> > Works fine:
> > 1、触控板，各种手势正常使用
> > 2、cfg解锁正常，地址还是0x3E
> > 3、蓝牙热启动正常
> > 4、无线，有时开机后不能识别，再次重启后正常，间歇性问题，没有找到原因
> > Doesnt work:
> > 1、type-c接口，使用扩展坞，外接显示器无法识别
> 
> 我和你一样的配置。想请问下 你有没有试过外接4k显示器。
> 我改了dvmt 64m后会花屏，但是外接4k显示器始终开不了hidpi。之前以为开了，但是后来发现都不是hidpi。只是有了比较高的分辨率，而且还模糊。


我没有shi

**Comment by Hongfumal** [comment]
> > Matebook 14 2020
> > CPU:i5 10代
> > RAM: 16G
> > SSD: SN750 黑盘
> > Macos Version：big11.2.1
> > EFI Version: 20210130
> > bios：1.19
> > Works fine:
> > 1、触控板，各种手势正常使用
> > 2、cfg解锁正常，地址还是0x3E
> > 3、蓝牙热启动正常
> > 4、无线，有时开机后不能识别，再次重启后正常，间歇性问题，没有找到原因
> > Doesnt work:
> > 1、type-c接口，使用扩展坞，外接显示器无法识别
> 
> 我和你一样的配置。想请问下 你有没有试过外接4k显示器。
> 我改了dvmt 64m后会花屏，但是外接4k显示器始终开不了hidpi。之前以为开了，但是后来发现都不是hidpi。只是有了比较高的分辨率，而且还模糊。

我们没有 试过 4k，现在我这边外输出 试过 1920，2k的没有问题，type-c接口，使用扩展坞的这个现在已经解决

**Comment by Hongfumal** [comment]
> 对了🤩🤩🤩看到你说你想帮帮忙，我这有两个东西让我蛋疼了一段时间，有没有兴趣研究一下？
> 
> 1. 摄像头:摄像头部分能用部分不能用，这个问题是华为的采购不同厂商摄像头导致的，但是uvc协议是通用的，加上10年前华硕的机子的黑苹果就有过类似的事，通过仿冒来解决，因此猜测是macos的usb扩展相关中可能有个厂商白名单，但是我们仿冒过了也无效，所以你有没有兴趣帮忙验证下我的白名单这一说，还有就是能不能找找能更改硬件vid以及pid的便于普及的办法？(拆下来用工程软件刷的那个不用了…也没有普及的能力)
> 2. 15w功耗限制以及最优变频以及耗电问题，这个属于一个不可完美三角，上述三个问题单独解决都很简单，但是同时兼顾就工程量很大，15w功耗限制我觉得可以给它去了，因为i7-8565这个u最大可以给到25w的tdp而且matebook14/13这个模具有很好的散热潜力，应该能通过改pl1和pl2就轻松解决(比如瞬时boost最高25w，长期boost最高18w这样)，然后，变频这个最麻烦，因为变频幅度与耗电成正比例，运行频率的大小也与耗电成正比例，最低设得太小最高设的太大会反而更费电，我是希望能找个平衡三者的最优解，但是我比较懒🤣🤣🤣你有兴趣找吗

这个 摄像头问题 我在之前 在远景论坛中看到过一个方案，现在帖子找不到。当时我印象是 通过一个 kext 修改 vid和pid，现在你那里有好的方案吗？
