### ISSUE TITLE
hdmi外接，休眠后再唤醒，无信号输出 MB14 2020（个例？有没有一样问题的，来留个言）

### ISSUE THREAD

**Issue by seils1984** [ske1996/matebook-13-2019-oc-efi#138]
*BEFORE YOU REPORT A BUG,ENSURE YOU DID READ ALL ISSUE OF MY REPO.  (casue maybe there was someone had reported same problem and i replied him/her)    
⚠️If you dont follow those option under this page when you report a issue,i will delete it without any notice

*请确定你在提交issue去报告一个bug前，你有认真读过我写的所有注意事项，并且读过这个项目里所有issue（因为可能已经有人提交过一样的了）
⚠️不按以下格式提交的一律删除处理

**Device info（设备信息）**

Matebook 14 2020
CPU: i5 10210
RAM: 16G
SSD: SN730
Macos Version：11.2
EFI Version: 20201113

**Describe the bug（问题简述）**
hdmi接口休眠后在启动，无法唤醒，主屏幕亮了，但是hdmi的屏幕不亮，需要插拔一次才行。
启动参数设置了igfxonln=1没有效果

**To Reproduce（详述问题发生前的操作）**
休眠后等屏幕暗掉，再唤醒能够重现。

**Screenshots（截图）**

**Additional context（其他附件事项）**

**Comment by ske1996** [comment]
………
你插上电用，或者百度搜mac外接休眠，你也能看到白苹果跟你一样，苹果的逻辑策略

**Comment by seils1984** [comment]
白苹果不一样 家里有一台2014的mbp 公司的是2019的mbp 都能够正常唤醒。
视频如下

https://user-images.githubusercontent.com/17974505/110061828-322ec800-7da3-11eb-978c-20f232789807.mov


https://user-images.githubusercontent.com/17974505/110061770-188d8080-7da3-11eb-9859-66964cc3d4e7.mov

**Comment by ske1996** [comment]
我明白了，不好意思啊之前理解错了，我想问唤醒后不是不输出了吗，那如果重新拔插还可以继续输出信号吗

**Comment by ske1996** [comment]
不好意思啊，我明白你的意思了，之前理解错了，以为是你想在睡眠后继续输出外接信号，你这个问题等我测试一下看看

**Comment by ske1996** [comment]
我测试了一下，你说的问题没出现啊。。。。虽然我自己用的efi有一些跟公开版不一样，但是boot args里面我没有加东西，基本跟0130那一版的efi对齐，我只是解锁了dvmt然后缓冲帧删除了预习加载32m以及2048缓存的选项
我做的操作基本与https://github.com/ske1996/matebook-13-2019-oc-efi/issues/121中最后跟他说的一致

**Comment by ske1996** [comment]
虽然不知道如何解决你的问题，也不知道你有没有改什么，试试把休眠模式设置成03，然后加载这个驱动
[HibernationFixup-1.3.4-RELEASE.zip](https://github.com/ske1996/matebook-13-2019-oc-efi/files/6107747/HibernationFixup-1.3.4-RELEASE.zip)
然后reset nvram试试

**Comment by ske1996** [comment]
对了，whatevergreen没必要用最新的哈，实在不行你一个一个降级去测试都行。

**Comment by 378210331** [comment]
非个例。matebook14 早在15.6时期就是这样了，修复了缓存帧只能保证睡眠前，睡眠后都要重新插拔，平时我都说外接显示器日常睡眠使用，为此都放弃了黑它了..

**Comment by ske1996** [comment]
> 非个例。matebook14 早在15.6时期就是这样了，修复了缓存帧只能保证睡眠前，睡眠后都要重新插拔，平时我都说外接显示器日常睡眠使用，为此都放弃了黑它了..

额……我再多找俩人看看吧，这问题我这测试没有啊………

谢谢你的回复~

**Comment by ske1996** [comment]
试一下这个，应该hdmi可以直接输出，我这里没有睡眠后唤醒的问题，看看你们换了这个以后有没有

**Comment by seils1984** [comment]
> [MB14　2020　缓冲帧2.plist.zip](https://github.com/ske1996/matebook-13-2019-oc-efi/files/6141856/MB14.2020.2.plist.zip)

之前就有试过 还是一样，现在拿黑苹果做生产机在使用，懒得折腾了，万一环境都没了就麻烦了。
不行matebook卖了 入m1 air 真香。
不过还是非常感谢你

**Comment by seils1984** [comment]
另外intel的wifi还是不稳定，偶尔连不上，而且有时候网络连着，但是不能访问外网，需要dhcp释放一下才能联网，可能是arp的缓存没有清除掉。 真希望华为能开放使用非cnvi的网卡，然后就可以用airdrop和连接罗技鼠标了。

**Comment by ske1996** [comment]
> 另外intel的wifi还是不稳定，偶尔连不上，而且有时候网络连着，但是不能访问外网，需要dhcp释放一下才能联网，可能是arp的缓存没有清除掉。 真希望华为能开放使用非cnvi的网卡，然后就可以用airdrop和连接罗技鼠标了。

其实是有的…分析过bios找到了cnvi的开关值，但是还有一层白名单……

**Comment by ske1996** [comment]
> > [MB14　2020　缓冲帧2.plist.zip](https://github.com/ske1996/matebook-13-2019-oc-efi/files/6141856/MB14.2020.2.plist.zip)
> 
> 
> 
> 之前就有试过 还是一样，现在拿黑苹果做生产机在使用，懒得折腾了，万一环境都没了就麻烦了。
> 
> 不行matebook卖了 入m1 air 真香。
> 
> 不过还是非常感谢你

额…不清楚你从哪里找的哈，这个我第一次发出来的……

**Comment by ske1996** [comment]
> > > [MB14　2020　缓冲帧2.plist.zip](https://github.com/ske1996/matebook-13-2019-oc-efi/files/6141856/MB14.2020.2.plist.zip)
> > 
> > 
> > 
> > 之前就有试过 还是一样，现在拿黑苹果做生产机在使用，懒得折腾了，万一环境都没了就麻烦了。
> > 
> > 不行matebook卖了 入m1 air 真香。
> > 
> > 不过还是非常感谢你
> 
> 额…不清楚你从哪里找的哈，这个我第一次发出来的……

这个缓冲帧来源是github id:laozhiang

**Comment by seils1984** [comment]
测了你给的plist，睡眠黑屏的问题解决了。
但是hdmi不起作用了，必须要typec转hdmi的口才能用。
我还是得斟酌下 到底放弃哪个。 好不容易有一个hdmi的口，多方便。
