### ISSUE TITLE
系统未知问题

### ISSUE THREAD

**Issue by PIndividual** [ske1996/matebook-13-2019-oc-efi#139]
**Device info（设备信息）**

Matebook 14 2020 i5-10210u

CPU: i5-10210u 
RAM:  16GB DDR3 2133MHZ
SSD:影驰 擎 1TB M.2
MacOS version: 10.15.7  
EFI version:OC 0.6.1

**Describe the bug（问题简述）**
最近发现黑苹果似乎变卡了，结果用hackintool一检查cpu发现什么信息都没有了，直接一片空白，我也不能查到之前解锁的cfg是否还有效，而且geekbench 5的cpu成绩掉了200多分
**To Reproduce（详述问题发生前的操作）**
我啥不该做的应该都没做
安装过一些软件，比如clean my mac X以及imazing
使用clean my mac进行过一次深度清理
**Screenshots（截图）**

**Additional context（其他附件事项）**

**Comment by PIndividual** [comment]
<img width="882" alt="Screen Shot 2021-03-08 at 7 17 55 PM" src="https://user-images.githubusercontent.com/62368342/110315103-c0c17480-8043-11eb-8832-7cd55b77edfc.png">
<img width="882" alt="Screen Shot 2021-03-08 at 7 18 26 PM" src="https://user-images.githubusercontent.com/62368342/110315114-c61ebf00-8043-11eb-8d8a-6a15a60f68fd.png">
<img width="882" alt="Screen Shot 2021-03-08 at 7 18 37 PM" src="https://user-images.githubusercontent.com/62368342/110315122-c7e88280-8043-11eb-958d-eb00bcd92eb9.png">

**Comment by ske1996** [comment]
1.config中机型设置改为 mbp16,2
2.一键cpufriend中设置为2000mhz，最大性能，然后别忘了在config中开启加载
3.关闭sip
4.解锁cfg后并修改config，顺着教程关闭那奖项
5.reset nvram

**Comment by PIndividual** [comment]
config改机型可以直接通过hackintool进行吗？

**Comment by PIndividual** [comment]
顺带问下大佬，第四步中的顺着教程关闭那两项，指的是什么a……

**Comment by PIndividual** [comment]
你的那张图，加载不全了……

**Comment by ske1996** [comment]
> 你的那张图，加载不全了……

挂vpn应该就能看到了，我也去重新看一下外链问题，其实就是那个kernel/quirks里面的前两项

**Comment by yliuhz** [comment]
matebook13 18-19也遇到了莫名变卡的问题，排查应该是AC9560网卡的锅，拆机重新插拔网卡可解
