### ISSUE TITLE
BigSur OC引导选项问题

### ISSUE THREAD

**Issue by lxy6515** [ske1996/matebook-13-2019-oc-efi#141]
华为book14  2020 安装完成黑苹果  两个问题1. 有时候连接wifi手机成功,电脑连接(显示成功)没网络,华为p30手机开热点无法使电脑有网络(连接成功);2.以OC 引导windows失败(在进入windows转圈动画时) ,只能进bios设置启动项 ,重新启动,OC只能引导黑苹果,Windows引导失败

**Comment by ske1996** [comment]
https://openintelwireless.github.io/itlwm/FAQ.html

Wifi问题按这个里面的faq自己排查

**Comment by ske1996** [comment]
OC引导windows去读我安装后的注意事项

**Comment by ske1996** [comment]
下次提交issue不按我写的格式(bug report)提交，将直接做删除处理
