### ISSUE TITLE
11.2系统cpu睿频不可以用

### ISSUE THREAD

**Issue by pzw1999** [ske1996/matebook-13-2019-oc-efi#142]
bigsur目前无法睿频，更换的其他版本的cpufriend也无法改善，用inter power gadget监视一直不动，电脑型号matebook13 2019款，处理器i3-8145u,其他功能正常。

**Comment by ske1996** [comment]
给个视频看看。就是那个intel监视软件的，另外把你的efi放这里来我看看

**Comment by pzw1999** [comment]
![1615467178690](https://user-images.githubusercontent.com/50543440/110790245-70f6cf00-8236-11eb-8dc6-81fb0fd98080.jpg)
怎么挂视频，不会呀

**Comment by ske1996** [comment]
把视频拖进这个打字的对话框里就行，录个30s就好，上传你的efi也是一样的操作

**Comment by pzw1999** [comment]
只能挂图片呀

**Comment by ske1996** [comment]
你的ipg咋也有bug啊，就算睿频出问题也不可能读出来频率跟功耗是0啊……

**Comment by ske1996** [comment]
点左上角的"intel powet gedget"然后更新一下那个软件

**Comment by pzw1999** [comment]
不清楚，引导文件直接从你的仓库里下载的呀，就在文件夹添加了几张图片，其他没动

**Comment by ske1996** [comment]
https://github.com/ske1996/matebook-13-2019-oc-efi/issues/121

这个issue里就有视频

先更新你的ipg

然后告诉你你用的efi版本号

以后提交issue用那个bug report
我给了格式的

**Comment by pzw1999** [comment]
[Uploading EFI.zip…]()

**Comment by ske1996** [comment]
第一，你要等他上传完再点发送……

你的efi的版本用的是哪个？就是我给的efi的版本号，告诉我

**Comment by ske1996** [comment]
主要是你更新ipg后的拍的视频

**Comment by pzw1999** [comment]
<img width="441" alt="截屏2021-03-11 下午9 11 53" src="https://user-images.githubusercontent.com/50543440/110792487-70018400-82ae-11eb-892e-0fd2727e18ad.png">

**Comment by pzw1999** [comment]
一直这个样子 oc：065

**Comment by pzw1999** [comment]
[EFI.zip](https://github.com/ske1996/matebook-13-2019-oc-efi/files/6123168/EFI.zip)

**Comment by ske1996** [comment]
我的意思是说你的ipg的版本太旧了，就是intel power gadget，去给他更新一下，你这个看起来也有bug，因为不可能功耗是0

**Comment by pzw1999** [comment]
可以了，设置里没弄好

**Comment by pzw1999** [comment]
<img width="380" alt="截屏2021-03-11 下午9 24 39" src="https://user-images.githubusercontent.com/50543440/110794005-3af63100-82b0-11eb-91b2-e417ad118409.png">

**Comment by ske1996** [comment]
你的睿频没问题

**Comment by pzw1999** [comment]
ok

**Comment by pzw1999** [comment]
<img width="656" alt="6065148D7FACB74FDB5612C78B15D6C7" src="https://user-images.githubusercontent.com/50543440/110795006-4bf37200-82b1-11eb-9cf9-2971478f5595.png">

**Comment by pzw1999** [comment]
执行运算没反应

**Comment by ske1996** [comment]
关闭sip

**Comment by pzw1999** [comment]
好的，都解决了。

我把项目地址在视频下面重新发到评论区了，另外，别拉黑我呀，不问你问题就是了😂😂
