### ISSUE TITLE
Intel Wireless- AC 9560 Wi-Fi驱动不佳

### ISSUE THREAD

**Issue by Chin-Me** [ske1996/matebook-13-2019-oc-efi#147]
**Device info（设备信息）**

Matebook 14 2019  
CPU:intel Core i7-8565U
RAM:8GB
SSD:WDC PC SN720 SDAPNTW-512G-1127
Macos Version：macOS  Big Sur 11.0.1 (20B29)
EFI Version:20210103

**Describe the bug（问题简述）**
Intel Wireless- AC 9560 160MHz Wi-Fi驱动不佳，只有很小概率能够驱动，也就是说有时候开机能连Wi-Fi，但是每次开机都是能够搜到Wi-Fi的，极少情况下成功驱动时也只有30Mbps的下载速率，而我windows下可以跑200Mbps。因为在杂项里看到了一个同型号的网卡的图片，所以怀疑是不是有什么特殊情况？还是说MateBook14 2019都是这款网卡？

**To Reproduce（详述问题发生前的操作）**
Wi-Fi驱动不佳

**Screenshots（截图）**
<img width="1440" alt="Screen Shot 2021-04-18 at 3 11 58 PM" src="https://user-images.githubusercontent.com/82708605/115137410-8d1d3580-a058-11eb-804d-e84a72dc7fbe.png">驱动成功时
![IMG_1371](https://user-images.githubusercontent.com/82708605/115138106-b5a72e80-a05c-11eb-8c07-f4844e5f90d6.jpeg)
驱动失败时

**Additional context（其他附件事项）**
CFG锁已解锁，应该跟这个无关吧

**Comment by Chin-Me** [comment]
我自己初步推断是项目里写了的“任何情况下都要杜绝热启动，不然会导致Wi-Fi和蓝牙失效，但是我自己没有重启过，要说大概只有去掉-v后，reset nvram自动重启了，如果是这个的问题，现在应该如何补救呢？重新替换EFI也试过了无效，补救后又要怎么防止下次reset nvram再次出现这种情况呢？谢谢

**Comment by ske1996** [comment]
readme/可正常工作的部件/点击展开wifi

我写了驱动作者

去更新下wifi驱动

**Comment by ske1996** [comment]
btw,你那个驱动失败的样子很像是从windows切换过来导致的
