### ISSUE TITLE
[bug解决] matebook14 2020,休眠后无法唤醒HDMI外接显示器

### ISSUE THREAD

**Issue by 378210331** [ske1996/matebook-13-2019-oc-efi#148]
**Device info（设备信息）**

Matebook 14 2020  

CPU:  i5-10210u
RAM:  16g
SSD: 西数SN730
MacOS version:  11.2.3 
EFI version:20201113

**Describe the bug（问题简述）**
原matebook 14 hdmi 外接显示器，睡眠-> 唤醒，无法唤醒外接显示器，只能唤醒笔记本显示器。
对于合盖当台式用的场景很不方便。

解决方案: 修改config.plist中启动参数加入 "igfxonln=1" ,修复睡眠唤醒黑屏问题。参考资料:
http://bbs.pcbeta.com/viewthread-1859580-1-1.html
参数完整路径:

<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
			<dict>
				<key>SystemAudioVolume</key>
				<data>Rg==</data>
				<key>boot-args</key>
				<string>igfxonln=1 debug=0x100 keepsyms=1 alcid=21</string>
				<key>run-efi-updater</key>
				<string>No</string>
				<key>csr-active-config</key>
				<data>AAAAAA==</data>
				<key>prev-lang:kbd</key>
				<string>en-US:0</string>
			</dict>
，修改完后reset nvram ,即可。
reset nvram 参考https://www.bilibili.com/read/cv7392829/

**Comment by ske1996** [comment]
你这啥也没写是啥意思？

**Comment by 378210331** [comment]
> 你这啥也没写是啥意思？

鼠标点得太快提交了。。。

**Comment by ske1996** [comment]
谢谢你的report，我明天测试下看看，这个问题我还真没太关注过，问题确认后我会更新一版efi

**Comment by 378210331** [comment]
> 谢谢你的report，我明天测试下看看，这个问题我还真没太关注过，问题确认后我会更新一版efi

另外，我用AirportItlwm v1.3.0 stable 无法打开wifi,现在用的v2.0.0-alpha 版本可以跑到我的宽带峰值20M/s而且很稳...

**Comment by ske1996** [comment]
> > 谢谢你的report，我明天测试下看看，这个问题我还真没太关注过，问题确认后我会更新一版efi
> 
> 
> 
> 另外，我用AirportItlwm v1.3.0 stable 无法打开wifi,现在用的v2.0.0-alpha 版本可以跑到我的宽带峰值20M/s而且很稳...

+1，我用1.3也崩了一回，就是wifi接口里面的打开关闭或者是连接热点都无效了，想新建个wifi的接口直接发现接口没了，所以推测是接口建立的问题，不过也没啥大事，就是按z大项目里的trouble shoting里面的流程来一套就行了

**Comment by ske1996** [comment]
对了，你的whatevergreen的版本是多少啊

**Comment by 378210331** [comment]
> 对了，你的whatevergreen的版本是多少啊

没改，就是用的20201113的版本

**Comment by ske1996** [comment]
我放了一个新的release，不过我改了一下缓冲帧，没用nvram注入的方式，你看看对你有没有效

**Comment by 378210331** [comment]
> 我放了一个新的release，不过我改了一下缓冲帧，没用nvram注入的方式，你看看对你有没有效

更改三码替换了有效果。
