### ISSUE TITLE
【经验/方案】cfgunlock真的下载不了

### ISSUE THREAD

**Issue by LPPDBD** [ske1996/matebook-13-2019-oc-efi#15]
![Uploading 88359970...]()

**Comment by ske1996** [comment]
你的图片挂了。
要等待上传完成再按提交

**Comment by ske1996** [comment]
因为你在国内下载不了就挂个vpn试一下

**Comment by LPPDBD** [comment]
> 因为你在国内下载不了就挂个vpn试一下

好的

**Comment by ske1996** [comment]
另外，你可以下载我的整个库
<img width="1164" alt="截屏0002-07-24 13 17 18" src="https://user-images.githubusercontent.com/63181546/88360309-1b0d0e00-cdb0-11ea-8bd8-ad8b613a0415.png">

**Comment by ske1996** [comment]
有很多办法可以系在的，自己多点点多试试都会知道的，这种问题你在百度搜都能搜到。这个网站又不是我创建的

**Comment by jiaogger** [comment]
可以下载的，我也是国内

**Comment by LPPDBD** [comment]
> 可以下载的，我也是国内
我搞了个VPN，搞定了
