### ISSUE TITLE
Matebook14 2020版，BIOS版本1.25 可以解锁CFG吗？

### ISSUE THREAD

**Issue by luoei** [ske1996/matebook-13-2019-oc-efi#151]
Matebook 14 2020

CPU: i5
RAM: 三星16g
SSD:东芝512
MacOS version: 11
EFI version: 1.25

原来是1.19，后来升级到了1.25

**Comment by ske1996** [comment]
说起来地址应该是没变的，但是我建议你自己分析一下看看，这样比较保险
