### ISSUE TITLE
Matebook 13 2020 触摸屏驱动异常

### ISSUE THREAD

**Issue by totoro447** [ske1996/matebook-13-2019-oc-efi#153]
Matebook 13 2020  

CPU:i5 10210U  
RAM: 16GB
SSD:东芝
MacOS version:11.4   
EFI version:OC0.6.5

问题描述：
matebook13 2020款是有触摸屏的，但是使用matebook13 2020的efi进入mac os不能使用触摸屏，其他均正常
接下来换成matebook14 2020的efi，一进去可以使用触摸屏，但是过一段时间便不能使用连同触摸板，再过几分钟，外接鼠标只能移动和使用右键，左键无法使用。重启后继续循环该问题。

**Comment by ske1996** [comment]
efi不要串着用。
你触摸屏不能驱动也是故意为之，为了稳定。
