### ISSUE TITLE
Matebook 13 2020使用状况

### ISSUE THREAD

**Issue by totoro447** [ske1996/matebook-13-2019-oc-efi#154]
Matebook 13 2020  
CPU:i5 10210U
RAM:16GB
SSD:东芝
Macos Version：11.4
EFI Version:0.6.5

Works fine:除了那三个无法始终修复的问题以外和新发现的触摸屏无法驱动以外，其余工作正常

Doesnt work:三个无法始终修复的问题以外和新发现的触摸屏无法驱动

扯点可能没什么用的经验：
如果嫌开机按F12切换系统麻烦的话，可以使用Refind uefi引导Windows UEFI 和 OC

**Comment by ske1996** [comment]
用windows多就设置win为默认，mac多就设mac为默认，关闭oc里的showpicker。

何必次次开机都要去看一次引导菜单。
我不觉得这个世界上会有人一天切换系统十几次。
毕竟装双系统不是为了切着玩的。
越少越原生的设置越好。
