### ISSUE TITLE
Matebook13 2019 i7-8565u OTA

### ISSUE THREAD

**Issue by relumine** [ske1996/matebook-13-2019-oc-efi#158]
*BEFORE YOU REPORT A BUG,ENSURE YOU DID READ ALL ISSUE OF MY REPO.  (casue maybe there was someone had reported same problem and i replied him/her)    
⚠️If you dont follow those option under this page when you report a issue,i will delete it without any notice

*请确定你在提交issue去报告一个bug前，你有认真读过我写的所有注意事项，并且读过这个项目里所有issue（因为可能已经有人提交过一样的了）
⚠️不按以下格式提交的一律删除处理

**Device info（设备信息）**

Matebook 13 2019 

CPU:  i7-8565u
RAM:  8GB
SSD: 西数512GB
MacOS version:   11.2.3 Bigsur
EFI version:OpenCore 0.6.5

**Describe the bug（问题简述）**
在系统的更新设置界面下载更新重启后，会有开机的苹果界面，有剩余时长，但是启动之后系统版本不变没有更新成功。

**To Reproduce（详述问题发生前的操作）**
无

**Screenshots（截图）**
<img width="668" alt="image" src="https://user-images.githubusercontent.com/46735748/122048725-380d5e00-ce14-11eb-89f6-0447f14bc19c.png">

**Additional context（其他附件事项）**

**Comment by ske1996** [comment]
关闭showpicker，重启后选macos installer或者是macintosh hd

**Comment by relumine** [comment]
好了 谢谢🙏
