### ISSUE TITLE
2020 matebook 14 i5 触摸板使用参考

### ISSUE THREAD

**Issue by luoei** [ske1996/matebook-13-2019-oc-efi#159]
Matebook 14 2020

CPU:  i5
RAM:  16
SSD: 512 东芝
MacOS version: 11.3    
EFI version: 20210508

**Describe the bug（问题简述）**
触摸板可以使用，但是无法使用拖拽，就有点小难受，比如把一个文件拖拽到另外一个文件夹，按住文件准备拖的时候就打开预览或者打开文件了，浏览器复制多行文本也会自动打开文本翻译，导致无法继续复制。其它触摸板事件目前都正常使用，屏幕触摸也可以使用，但是不好用，在电脑操作系统上面。

非常感谢作者的辛苦付出，不知道有没有解决一下这个问题？非常感激。

**Comment by ske1996** [comment]
这个不是问题或者bug

设置/触控板
进去以后第一页最上面的三项要打钩，最下面的两项不打钩就行了

**Comment by luoei** [comment]
> 这个不是问题或者bug
> 
> 设置/触控板
> 进去以后第一页最上面的三项要打钩，最下面的两项不打钩就行了

果然，多谢哈
