### ISSUE TITLE
MateBook14 2019运行macOS Big Sur完美运行，解决花屏问题

### ISSUE THREAD

**Issue by Bylee0** [ske1996/matebook-13-2019-oc-efi#160]
Matebook 14 2019
CPU:intel Core i7-8565U
RAM:8GB
SSD:WDC PC SN720 SDAPNTW-512G-1127
macOS Version：macOS Big Sur 11.2
Works fine:
蓝牙,Wi-Fi,睡眠,触控板,CPU变频等都工作正常
Doesnt work:
硬件方面还是MX250,指纹和摄像头这三样用不了,修改完分辨率，发现高分辨率关机，睡眠唤醒花屏，EFI
显卡型号（Intel Iris Plus Graphics 655），打成（Intel UHD Graphics 620）后使用1600x1066完美显示不花屏。
<img width="653" alt="截屏2021-06-27 下午3 43 05" src="https://user-images.githubusercontent.com/86549117/123536722-a3cdc000-d75e-11eb-8985-a71a71d3fc36.png">
![Uploading 截屏2021-06-27 下午3.55.18.png…]()

**Comment by Bylee0** [comment]
<img width="958" alt="截屏2021-06-27 下午3 55 18" src="https://user-images.githubusercontent.com/86549117/123537279-2eafba00-d761-11eb-9192-d77e0d607eaa.png">

**Comment by ske1996** [comment]
首先，谢谢你的想解决问题的心意。

但是睡眠唤醒花屏跟缓冲帧的model的值没有关系。写成655也不是写错，是故意为之。

而且我有给出各个版本的缓冲帧予以参考。

故此，我会关闭此issue，因为说的不对，有误导人的可能
