### ISSUE TITLE
matebook14 2020安装Monterey跑第二组代码无限重启 

### ISSUE THREAD

**Issue by redstar12138** [ske1996/matebook-13-2019-oc-efi#161]
**Device info（设备信息）**

Matebook 14 2020  

CPU:  i5 10210U
RAM:  16G
SSD: SN730
MacOS version:   Bigsur 11.5 beta
EFI version: 20210508

**Describe the bug（问题简述）**
11.5 beta 按 #155 操作跑代码第一次之后,开-v或者不开,重启第二次均至截图界面无限重启

**To Reproduce（详述问题发生前的操作）**
直接ota

**Screenshots（截图）**
![1625305581884](https://user-images.githubusercontent.com/49825040/124350318-9add6280-dc26-11eb-9c3b-5fb2f0d3b894.jpg)

**Comment by ske1996** [comment]
config发上来我看一眼

**Comment by redstar12138** [comment]
OTA的public beta 1
![38FA4F88-A6B4-40D2-B775-30D9CA4227B2](https://user-images.githubusercontent.com/49825040/124371264-a5453e00-dcb2-11eb-9b54-b2dda786b435.png)

kext由0508的release直接更改
<img width="446" alt="image" src="https://user-images.githubusercontent.com/49825040/124371222-26e89c00-dcb2-11eb-8b6d-c9b6493e4e06.png">

尝试过的config(bigsur均可正常引导)
[config.zip](https://github.com/ske1996/matebook-13-2019-oc-efi/files/6759279/config.zip)

**Comment by ske1996** [comment]
仔细再去读一下我写的东西
我给出的东西你没有加载全

也可以顺便把所有的kext都更新成最新的alpha，然后清空nvram

**Comment by redstar12138** [comment]
config内securebootmodel改为disabled，关闭-v模式后Reset nvram更新成功，但启动时卡代码
![PXL_20210706_181848342](https://user-images.githubusercontent.com/49825040/124696314-6663f200-df17-11eb-96f6-73a152b67dd5.jpg)

**Comment by Andresruizj** [comment]
Do u find a solution??

**Comment by ske1996** [comment]
> config内securebootmodel改为disabled，关闭-v模式后Reset nvram更新成功，但启动时卡代码
> ![PXL_20210706_181848342](https://user-images.githubusercontent.com/49825040/124696314-6663f200-df17-11eb-96f6-73a152b67dd5.jpg)

你看懂了什么叫“更新完后再改回Default”吗？
眼睛不要可以捐给有需要的人，别整的跟我教你的东西就是有问题你就来赖我一样
