### ISSUE TITLE
macbook14 2020 睡眠唤醒有几率失败

### ISSUE THREAD

**Issue by kuniseichi** [ske1996/matebook-13-2019-oc-efi#162]
**Device info（设备信息）**

Matebook 14 2020
![image](https://user-images.githubusercontent.com/24471057/124409380-c6716180-dd7a-11eb-8da9-e545c3a7551c.png)

MacOS version:   15.7
EFI version: oc 0.6.5

**Describe the bug（问题简述）**
笔记本盒盖外接显示器，此时正常，随后直接拔掉hdmi接口，然后开盖，屏幕不亮，强制重启后显示如下报错
![image](https://user-images.githubusercontent.com/24471057/124409300-a477df00-dd7a-11eb-91ed-a6aea6028166.png)

**Comment by ske1996** [comment]
你这角度还挺清奇的……

https://github.com/ske1996/matebook-13-2019-oc-efi/issues/148

我没遇到过你那个问题，你参考这个试一下

**Comment by zhang-jia-hui** [comment]
我想问一下，我的事matebook13 2020 也是休眠之后无法点亮屏幕但不是外接显示器

**Comment by zhang-jia-hui** [comment]
是开启hidpi之后才有的问题

**Comment by ske1996** [comment]
> 我想问一下，我的事matebook13 2020 也是休眠之后无法点亮屏幕但不是外接显示器

1.重启后的日志
2.设置/显示器里执行的hidpi的分辨率
3.拍个视频，完整的录下整个过程

你这个问题不对。按我写的教程走不可能这样。应该是你那里没做好，或者是说你的唤醒与hidpi无关，但是你以为有关系。我测试过你那个机型。

**Comment by ske1996** [comment]
> **Device info（设备信息）**
> 
> 
> 
> Matebook 14 2020
> 
> ![image](https://user-images.githubusercontent.com/24471057/124409380-c6716180-dd7a-11eb-8da9-e545c3a7551c.png)
> 
> 
> 
> MacOS version:   15.7
> 
> EFI version: oc 0.6.5
> 
> 
> 
> **Describe the bug（问题简述）**
> 
> 笔记本盒盖外接显示器，此时正常，随后直接拔掉hdmi接口，然后开盖，屏幕不亮，强制重启后显示如下报错
> 
> ![image](https://user-images.githubusercontent.com/24471057/124409300-a477df00-dd7a-11eb-91ed-a6aea6028166.png)
> 
> 

24小时内未回复，关闭issue
