### ISSUE TITLE
matebook13 2020 i7 盖上盖子休眠之后黑屏无法唤醒

### ISSUE THREAD

**Issue by zhang-jia-hui** [ske1996/matebook-13-2019-oc-efi#163]
**Device info（设备信息）**

Matebook 13 2020

CPU:  i7
RAM:  16
SSD:512
MacOS version:   11.2 bigsur
EFI version:  MateBook13-2020.20210508.7z

**Describe the bug（问题简述）**
matebook13 2020 i7 在开启HIDPI之后，盖上盖子休眠之后黑屏无法唤醒,然后强制关机在启动进入桌面之后弹出来了一个原因：
Sleep Wake failure in EFI

Failure code:: 0x00000000 0x001a001f

Please IGNORE the below stackshot

================================================================
Date/Time:        2021-07-12 10:53:15.033 +0800
OS Version:       ??? ??? (Build ???)
Architecture:     x86_64
Report Version:   32

Data Source:      Stackshots
Shared Cache:     A33707D1-FC47-30FB-A239-A6AFA68DA7C0 slid base address 0x7fff200b0000, slide 0xb0000

Event:            Sleep Wake Failure
Duration:         0.00s
Steps:            1

Boot args:        debug=0x100 keepsyms=1 alcid=21 chunklist-security-epoch=0 -chunklist-no-rev2-dev

Time Awake Since Boot: 17s

Process:          swd [319]
Architecture:     x86_64
Footprint:        364 KB
Time Since Fork:  1s
Num samples:      1 (1)

  Thread 0x99a    1 sample (1)    priority 4 (base 4)
  <thread QoS background (requested background), thread darwinbg, process darwinbg, IO tier 2>
  1  start + 1 (libdyld.dylib + 87585) [0x7fff203dc621] 1
    1  ??? [0x10aaae454] 1
      1  ??? [0x10aaae1e8] 1
        1  __stack_snapshot_with_config + 10 (libsystem_kernel.dylib + 143386) [0x7fff203af01a] 1
         *1  ??? [0xffffff80002601f6] 1
           *1  ??? [0xffffff80009698cb] 1
             *1  ??? [0xffffff80008733c1] 1
               *1  ??? [0xffffff80002831c9] 1
                 *1  ??? [0xffffff80002ba3ed] (running) 1

  Binary Images:
        0x7fff2038c000 -     0x7fff203bafff  libsystem_kernel.dylib (7195.81.3) <AB413518-ECDE-3F04-A61C-278D3CF43076>  /usr/lib/system/libsystem_kernel.dylib
        0x7fff203c7000 -     0x7fff20401fff  libdyld.dylib (832.7.3)            <4641E48F-75B5-3CC7-8263-47BF79F15394>  /usr/lib/system/libdyld.dylib
Model: MacBookPro15,2, BootROM 1554.60.15.0.0, 4 processors, Quad-Core Intel Core i7, 2.3 GHz, 16 GB, SMC 
Graphics: kHW_IntelIrisGraphics655Item, Intel Iris Plus Graphics 655, spdisplays_builtin
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, LPDDR3, 2133 MHz, SK Hynix, -
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, LPDDR3, 2133 MHz, SK Hynix, -
AirPort: spairport_wireless_card_type_airport_extreme (0x8086, 0x2034), itlwm: 1.2.0 fw: 48.1335886879.0
Bluetooth: Version 8.0.3d9, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Network Service: PgyMacClient, VPN (com.oray.pgy.PgyVisitorMac), utun2
PCI Card: Intel Iris Plus Graphics 655, VGA compatible controller, Internal@0,2,0
PCI Card: ALC256, Audio device, Built in
USB Device: USB 3.1 Bus
USB Device: Bluetooth HCI
USB Device: HD Camera
Thunderbolt Bus: 

**To Reproduce（详述问题发生前的操作）**
当时装好了之后就忘了继续看git上的文档了，最开始用那个switchResX折腾了折腾，后来也是用那个文档上说的注入方法只不过最开始看了一个别的视频用的是1500x1000，后来就改成1600x1066 1343x895 2160x1440了

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/67014721/125226350-832b6b80-e303-11eb-9d24-3b00c84a352d.png)
![image](https://user-images.githubusercontent.com/67014721/125226380-91798780-e303-11eb-925e-e17f0a6ee23f.png)

**Additional context（其他附件事项）**

**Comment by ske1996** [comment]
1. 有两张图，你现在的情况是哪个？
2. 出现问题时的hidpi分辨率执行的哪个？
3. 对我的efi做了什么改动？尤其是缓冲帧以及boot-args的部分
4. 更改hidpi数组时，有没有进行s/l/d的清理？
5. 目前开启hidpi用的脚本是哪里的？为什么不用我提供的那个？

**Comment by zhang-jia-hui** [comment]
1. 2.这两张图的意思是之前您要我重新发个帖子的时候您让我带上分辨率，两个分辨率都是一样的都是合上盖子休眠都会点不亮，但是不合上盖子休眠没有问题，
3.efi我没有做任何改动 我记得我是拿来直接用的，
4.这个我有点不太清楚 我是直接用的一个跟您这个一样的插件修改的分辨率，
5.这个是在网上找的一个插件http://www.360doc.com/content/20/0912/16/49522320_935285838.shtml，这个怪我当时我系统进来之后我以为就好了没有再继续下边的步骤了，知道发现屏幕有点发昏，然后就在网上找的解决方案，
6.是注入了的

**Comment by zhang-jia-hui** [comment]
> 能力有限，你的我看不出来东西
> 你写的东西太模糊了，回答一下下面的问题，一个不能少。
> 
> 1. 有两张图，你现在的情况是哪个？
> 2. 出现问题时的 hidpi 分辨率的哪个？
> 3. 对我efi还有什么改变？特别是缓冲帧以及boot-arg的部分
> 4. 更改hidpi数组时，有没有进行s/l/d的清理？
> 5. 现在开启hidpi用的剧本是哪里的？为什么不用我提供的那个？
> 6. 是否有注入？

1 .2.这两张图的意思是之前您要我重新发个帖子的时候您让我带上分辨率，两个分辨率都是一样的都是合上盖子休眠都会点不亮，但是不合上盖子休眠没有问题，
3.efi我没有做任何改动 我记得我是拿来直接用的，
4.这个我有点不太清楚 我是直接用的一个跟您这个一样的插件修改的分辨率，
5.这个是在网上找的一个插件http://www.360doc.com/content/20/0912/16/49522320_935285838.shtml，这个怪我当时我系统进来之后我以为就好了没有再继续下边的步骤了，知道发现屏幕有点发昏，然后就在网上找的解决方案，
6.是注入了的

**Comment by ske1996** [comment]
因为我确实是不知道你具体到都做了什么，所以按我下面写的做

1.清理s/l/d以及l/d中的overrides，以及删除任何可以调节hidpi的软件，并保证该软件的路径被彻底清空
2.关机10s后再开机，然后reset nvram
3.按我写的hidpi教程可丁可卯的做，包括使用的工具，不要想着小聪明

以上不行的话就格式化重装吧，并且格式化要彻底一点。
我还是那句话，这个机型我有，这么久了别人也都没问题，为什么就你有问题了对不对？说明不是我的问题。
