### ISSUE TITLE
matebook14 2020第一阶段安装完进不了系统

### ISSUE THREAD

**Issue by jasonziai** [ske1996/matebook-13-2019-oc-efi#166]
用的20210508的release，生成了三码，其他未动。bios关了安全选项。从U盘安装到硬盘后，选择macos硬盘启动闪一下logo直接重启了。-v无效果，还是出现logo看不到任何代码就重启了。保留硬盘分区结构没变，windows还在，d盘删了当mac盘，求大佬赐教

**Comment by ske1996** [comment]
不可能。

**Comment by jasonziai** [comment]
> 未按格式提交

用p...tree改的，应该没问题。我用0508efi这个插台式机引导recovery盘可以进入，应该格式没问题。但是-v也是没效果。懵逼了
