### ISSUE TITLE
关于Monterey显示分辨率的一点疑问

### ISSUE THREAD

**Issue by panshaodong** [ske1996/matebook-13-2019-oc-efi#169]
**Device info（设备信息）**

Matebook 13 2019

CPU: i7 8565U
RAM: 8G
SSD model:WDC PC SN720 SDAPNTW-512G-1027
MacOS version: Monterey beta6
EFI version:Matebook.13.2018-2019.20210811

**Describe the bug（问题简述）**
在系统还是Big Sur时，已经开启HIdpi，使用的分辨率是1600x1066（个人觉得这个分辨率字体大小较为适中）。升级到Monterey后，刚进入桌面时的分辨率是1600x1066的，但进入显示器设置后却没有了这个分辨率选项，大一点的是1920x1280，小一点的是1343x895，万一随便点了一个就没办选回1600x1066。我进入终端操作，先关闭Hidpi，再按照大佬的说明开启Hidpi，设置里面还是没有1600x1066分辨率的选项，如何能开启这一选项呢？

这只是个强迫症的疑问，见谅。请ske1996大佬帮忙看看，谢谢！

![image](https://user-images.githubusercontent.com/89829031/131634938-60a7c16b-88f9-4f02-bc1d-b5abdc3e2bf0.png)

**Comment by ske1996** [comment]
那你为什么不附上你设置的图呢？

你觉得找人问东西是不是应该尽可能的主动把跟问题有关的图提供全？

**Comment by panshaodong** [comment]
不好意思，不好意思！

![image](https://user-images.githubusercontent.com/89829031/131637227-b139ffa7-8904-4c3e-a3e5-457058b823c2.png)

![image](https://user-images.githubusercontent.com/89829031/131637285-2a386d27-48b2-48d2-a053-00e485a78790.png)

**Comment by ske1996** [comment]
中间不是还有两个选项吗？
把鼠标分别放在上面，分别截图看一下

**Comment by panshaodong** [comment]
![image](https://user-images.githubusercontent.com/89829031/131638572-bb1102e0-4370-4f25-871b-dd7219b3b5c1.png)

![image](https://user-images.githubusercontent.com/89829031/131638649-59765d0b-e5c3-4c0e-ac6f-478bbfab2370.png)

**Comment by ske1996** [comment]
我刚发现我也没有🤣🤣🤣

这个脚本实际上是偷懒的

你自己搜一下手动开hidpi的教程，很老。
你把那个看懂后，去手动改一下l/d里面的那个override(好像是叫这个)里面的.plist里面的参数，看看能不能出来。

教程就自己搜哈，我也没存

**Comment by panshaodong** [comment]
已经搞定，只要在用one-key-hidpi的时候，最后一步输入1600x1066 3200x2132，就可以了

<img width="725" alt="截屏2021-09-01 下午11 36 13" src="https://user-images.githubusercontent.com/89829031/131702546-3d315ad1-3308-4e69-ac35-540e09591063.png">

<img width="780" alt="截屏2021-09-01 下午11 32 05" src="https://user-images.githubusercontent.com/89829031/131702579-4a16ac36-3dcf-4da2-9125-b1643e3dfa9f.png">
