### ISSUE TITLE
我放了WIFI驱动，重建缓存就进不去系统了

### ISSUE THREAD

**Issue by LPPDBD** [ske1996/matebook-13-2019-oc-efi#17]
![image](https://user-images.githubusercontent.com/68722861/88448143-03e02600-ce6d-11ea-9867-057c70753015.jpeg)
就这样不出进度条

**Comment by ske1996** [comment]
跟我描述下你重建缓存，你都做了什么

**Comment by LPPDBD** [comment]
> 跟我描述下你重建缓存，你都做了什么

抱歉你回的太晚了，我没时间，等不急。

**Comment by ske1996** [comment]
Issue可以编辑，不要发两个出来还赖人说不理你，怎么使用github这个我觉得我必要教你

**Comment by ske1996** [comment]
老子没义务管你，自己菜不会玩就别玩黑苹果，我是你爹啊？我还得给你一天24待机秒回的？这么巨婴？没脑子不适合用电脑

**Comment by LPPDBD** [comment]
> Issue可以编辑，不要发两个出来还赖人说不理你，怎么使用github这个我觉得我必要教你
我没有赖别人不理我呀。

**Comment by LPPDBD** [comment]
> 老子没义务管你，自己菜不会玩就别玩黑苹果，我是你爹啊？我还得给你一天24待机秒回的？这么巨婴？没脑子不适合用电脑

你吃屎了吧？我要干啥关你屁事！我叫你回我消息了吗？自己贱嗖嗖的跑来说三道四，反而怪别人。我有要求你回我消息吗？我有要求你管我吗？
好声好气的跟你说话，你妈的也太给脸不要脸了吧。

**Comment by ske1996** [comment]
去找个三甲医院看看脑子，实在不行就去协和挂个号，打114可以电话预约
