### ISSUE TITLE
大佬是否会更新opencore 0.7.3

### ISSUE THREAD

**Issue by panshaodong** [ske1996/matebook-13-2019-oc-efi#172]
Matebook 13 2019

CPU: i7 8565U
RAM: 8G
SSD model:WDC PC SN720 SDAPNTW-512G-1027
MacOS version: Monterey beta6
EFI version:Matebook.13.2018-2019.20210811

Opencode最新发布了0.7.3版本和一些驱动的更新，请问ske1996大佬会做相关的OC升级和驱动更新吗？毕竟比现在的0.6.5版本相隔已经很多了。

**Comment by ske1996** [comment]
0.6.5以后的每一次的更新日志我都会看，可是对于boot以及安全上的东西针对我们八代u来说没有任何的更新

没有好处的时候何必去做呢对不对。kext的更新在自行下载后复制替换就好，没有任何技术含量，所以也没必要专门为了这个而发布新的release。

这个就是我的看法。

0.6.5挺好用的啊。。。最新不代表最好。。你可能没吃过那种更新了反而就废了的亏。。。
