### ISSUE TITLE
蓝牙鼠标能正常使用了

### ISSUE THREAD

**Issue by panshaodong** [ske1996/matebook-13-2019-oc-efi#173]
Matebook 13 2019

CPU: i7 8565U
RAM: 8G
SSD model:WDC PC SN720 SDAPNTW-512G-1027
MacOS version: Monterey beta6
EFI version:Matebook.13.2018-2019.20210811

在远景论坛上有人发布了OpenCode0.7.3和一些更新驱动，我把驱动下载了都替换到Kexts文件夹里，然后重启，然后发现我的小米蓝牙鼠标可以正常连接，正常使用。以前是可以发现鼠标，但就是连接不上，现在正常了，也不知道是不是更新驱动的原因，请大佬分析一下。

OpenCode0.7.3和一些更新驱动链接:https://pan.baidu.com/s/1x5JnXoGJvo22WhSZ2_Z3dQ 提取码:n28g

<img width="780" alt="截屏2021-09-08 上午3 40 01" src="https://user-images.githubusercontent.com/89829031/132404273-11ce59aa-6590-444e-be14-d8c95060daf2.png">

**Comment by ske1996** [comment]
你这个不叫蓝牙鼠标可以正常使用了。。。以前本来也可以，只是挑牌子。。。
蓝牙kext不是我开发的，所以这个问题我没法解答。
但是可以确定的告诉你，跟oc的版本没关系。

对了方便的话，可以请你在这个issue里分享一下鼠标的具体型号以及购买链接吗？
谢谢～
https://github.com/ske1996/matebook-13-2019-oc-efi/issues/156
