### ISSUE TITLE
Monterey beta7 触控板双指滚动时偶尔会失效的问题

### ISSUE THREAD

**Issue by panshaodong** [ske1996/matebook-13-2019-oc-efi#176]
Device info（设备信息）

Matebook 13 2019

CPU: i7 8565U
RAM: 8G
SSD model:WDC PC SN720 SDAPNTW-512G-1027
MacOS version: Monterey beta7
EFI version:Matebook.13.2018-2019.20210811

**Describe the bug（问题简述）**
升级beta7后，触控板双指滚动时偶尔会失效的问题，特别的在浏览网页时比较明显，双指向上滑着滑着突然间失效几下，就像卡顿了一样，一秒左右后正常。我试了edge和safari浏览器都是这样，应该不是浏览器的问题了。
请问大家有遇到这样的情况吗？请ske1996大佬分析一下，谢谢！

**Comment by panshaodong** [comment]
刷网页的时候已经不是偶尔了，是频繁，挺烦的

**Comment by ske1996** [comment]
😂确实不知道
我没有对触控板添加任何额外的ssdt，一直都是xosi加上i2c的几个kext就驱动好了。
所以可以确定里面没有ssdt的判定错误问题。

**Comment by ske1996** [comment]
如果你有什么发现请你在这里分享一下可以吗？近期我在写论文，所以不敢升级，也看不到怎么回事，没法上手摸

**Comment by panshaodong** [comment]
升级beta7也挺麻烦的，oc0.6.5会卡logo无限重启，找到方法是先退AppleID，改机型为17,1，升级好再改回机型，听说0.7.4已适配beta7。您先忙吧，有空再研究了。

**Comment by panshaodong** [comment]
今天更新到beta8，使用了几个小时，暂时没有偶尔失效的问题
