### ISSUE TITLE
你好，我安装的时候有个问题请教下

### ISSUE THREAD

**Issue by liutao-hue** [ske1996/matebook-13-2019-oc-efi#177]
我的笔记本是matebook13 2018-2019版本的，我用Matebook.13.2018-2019.20210811的EFI，安装的时候每次都卡在选择语言那，如图：
![7ae80f7a7b72c02739438536a027845](https://user-images.githubusercontent.com/75152458/135704296-ace9a883-404f-4be6-81e4-d2d0cd7f4e78.jpg)
请问改有什么办法解决吗？多谢

**Comment by ske1996** [comment]
没遇见过，重新写盘吧

**Comment by liutao-hue** [comment]
重新几次都是这样每次都卡在这，选择语言的页面出不来

**Comment by liutao-hue** [comment]
> 没见过，改盘吧

重来一次，每次都卡在这选择语言的页面出不来；我五月份的时候用你那个时候的 EFI 是能安装成功的，不过那个时候是刚出来的版本，你能发我一个那个时候的 EFI 吗，我那个时候能用上
