### ISSUE TITLE
MateBook D14 2020 Several problems: No sound, no exit from sleep

### ISSUE THREAD

**Issue by playXE** [ske1996/matebook-13-2019-oc-efi#178]
Matebook D14 2020
CPU:  i5 10210u
RAM:  8GB DDR4
SSD model: TOSHIBA 256
MacOS version:   Catalina 10.15.7
EFI release version: 20210811 (Latest)

**Describe the bug（问题简述）**
No sound and no proper exit from sleep. When I try to open laptop and press any key it is just black screen and nothing happens (except keyboard backlight, it works)
**To Reproduce（详述问题发生前的操作）**
1) Just boot to laptop and there's no sound.
2) Just close your laptop and open it after it goes to sleep

**Comment by ske1996** [comment]
are you kidding me？

frist,this repo is for MB13/14
second,you cant use mb13's efi file for mb d14
