### ISSUE TITLE
我的是19款的matebook13 i7 8565

### ISSUE THREAD

**Issue by LPPDBD** [ske1996/matebook-13-2019-oc-efi#18]

**Comment by ske1996** [comment]
补充一下你的运行状况，什么能用，什么不能用

**Comment by LPPDBD** [comment]
> 补充一下你的运行状况，什么能用，什么不能用

我现在准备格盘重装

**Comment by ske1996** [comment]
那你开这个issue是为了啥？

**Comment by LPPDBD** [comment]
> 那你开这个issue是为了啥？

我本以为会有人知道啥情况，但是没人理我

**Comment by ske1996** [comment]
自己看看你做了什么，这个issue里面只有你说了一句你电脑是啥就什么都没有了，你逗我玩呢？

**Comment by LPPDBD** [comment]
> 自己看看你做了什么，这个issue里面只有你说了一句你电脑是啥就什么都没有了，你逗我玩呢？

你觉得我要说点啥才正确？

**Comment by ske1996** [comment]
你去你开的另一个issue看看我有没有回你？

**Comment by ske1996** [comment]
结论就是，你开了两个issue，把这个当微信用了，一个issue说了问题，我也回你了，第二个issue你就光说你电脑是什么，我以为你要报告运行状况，所以我说让你说具体的
你去你发的另一个issue里看看我有没有理你？

**Comment by LPPDBD** [comment]
> 结论就是，你开了两个issue，把这个当微信用了，一个issue说了问题，我也回你了，第二个issue你就光说你电脑是什么，我以为你要报告运行状况，所以我说让你说具体的
> 你去你发的另一个issue里看看我有没有理你？
> 

对不起，大佬，我不会玩这个软件，我不懂你是啥意思？
