### ISSUE TITLE
期待摄像头问题能解决，不知道19款的14能不能同享

### ISSUE THREAD

**Issue by Voring** [ske1996/matebook-13-2019-oc-efi#2]

**Comment by ske1996** [comment]
你可以试试，我觉得14应该能用

另外摄像头是概率事件，有的机器就算不修复他的摄像头也能用

**Comment by Voring** [comment]
> 你可以试试，我觉得14应该能用
> 
> 另外摄像头是概率事件，有的机器就算不修复他的摄像头也能用

我用的efi是无法正常使用摄像头的，目前matebook的efi都是特定型号的可以用，1480可用，但大多数都是不可用的5075

**Comment by ske1996** [comment]
看来你对此也有了解

跟你聊聊我的思路，因为都是uvc通用协议我觉得没理由不能用
查了很多之后
觉得有两个点可以进行深入研究
第一个是摄像头分辨率低导致无法启动，这个或许可以通过调整系统采样的摄像头分辨率解决，有一个app叫cameracontrol，它可以调整采样分辨率，但是这个app过于久远，无法在10.15上使用，但是作者公开了源代码

第二个没有特别的原因，只是查到这家台湾的厂子也是华硕的供货商，而且华硕的笔记本很多采用这个厂子的摄像头的，在以前15-16年的黑苹果时，也是无法驱动摄像头，但是只要打上一个华硕专用的摄像头驱动(kext)就可以了，我在琢磨这个

**Comment by Voring** [comment]
很感谢你分享思路给我，不过我只是略知一二，对摄像头问题比较上心而已。能潜心解决摄像头问题的真的不多见了，很多人觉得摄像头无所谓，但在matebook的黑果交流群里还是经常有人问摄像头的，也有很多爱好者纠结于摄像头问题，总之加油！希望你能研究成功。

**Comment by ske1996** [comment]
对了，如果可以的话，麻烦你提交一下你的机器信息，配置，还有都有什么可用，重新开一个issue，这样可以帮助更多的人参考

**Comment by Voring** [comment]
> 对了，如果可以的话，麻烦你提交一下你的机器信息，配置，还有都有什么可用，重新开一个issue，这样可以帮助更多的人参考

不好意思啊，我用的是我加入的一个matebook群里的大佬做的的oc，慕摄像头的名来到这里，所以我应该没什么参考价值供来到这里的人参考。

**Comment by ske1996** [comment]
好的谢谢

请我可以告诉我群号吗

我想进去交流一下

**Comment by Voring** [comment]
加我qq交流，号码如下

**Comment by Voring** [comment]
1948048832

**Comment by ske1996** [comment]
你qq有验证问题的，把群号给我吧

**Comment by Voring** [comment]
好吧，无所谓了，我QQ就一个“你是”问题防止广告机器加我而已，随便填个什么都行。那你自己付费进群吧527454189

**Comment by ske1996** [comment]
好的谢谢

**Comment by Voring** [comment]
这种事不用谢哈

**Comment by aihanjiao** [comment]
@ske1996 @Voring 有一个年代稍微近点的[repo](https://github.com/Itaybre/CameraController)，两位大佬能否研究下
