### ISSUE TITLE
请教OC引导问题

### ISSUE THREAD

**Issue by baiyu0111** [ske1996/matebook-13-2019-oc-efi#21]
配置：matebook13 i5 8265U，硬盘：西数SN750
原本使用Clover作为引导，并成功安装10.15.6，今天在“黑果小兵”下载镜像“macOS Catalina 10.15.6(19G73) Installer for Clover 5119 and OC and WEPE”
该版本支持OC引导，现在使用Etcher将镜像写入16GU盘当中后，出现三个引导EFI、OC、WEPE，想要使用OC作为安装引导并在安装后使用OC作为引导，在安装前，我应该将您的OC引导文件“OpenCore EFI for boot(20200728)”中的EFI文件夹替换到上述EFI、OC、WEPE三个分区中的哪个呢，另问我是否需要删除另外两个不需要的引导分区呢。
谢谢您为此做出的共享，使得安装如此简单，非常感谢您整合的引导文件。

**Comment by baiyu0111** [comment]
上述说错了，原本使用Clover作为引导，并成功安装的是10.15.5，镜像名称为：macOS Catalina 10.15.5 19F96 With Clover 5118 and OC 0.5.9 Dual Boot Len's DMG

**Comment by ske1996** [comment]
不需要的不用删除，放哪里我说不清，你多截几幅图出来给我可那看哪路径。
老老实实用clover去安装，oc的安装过程跟clover的不一样。需要你自己琢磨
你可以用clover安装。然后用oc引导，我也是这么写的教程
