### ISSUE TITLE
【经验/方案】写盘完成后无法进入clover引导的问题，显示boot fail

### ISSUE THREAD

**Issue by Sugarcandy** [ske1996/matebook-13-2019-oc-efi#22]
我下载了群主推荐的系统版本，按照群主给的视频链接操作将系统写入到U盘后用genius打开磁盘进入efi如下：
![image](https://user-images.githubusercontent.com/40589172/88614923-603c8300-d0c3-11ea-9847-9bbe6ef46a25.png)

接着删除原有的clover文件夹，将群主给的efi文件的clover文件复制到磁盘efi下：
![image](https://user-images.githubusercontent.com/40589172/88615033-9f6ad400-d0c3-11ea-9edf-3b462ad9758a.png)

接着重启电脑，按F12选择U盘启动，一共三个选项，其他两个（windows+uefi）都是进微PEwin 端，最后一个（uefi1）就是boot fail........
![image](https://user-images.githubusercontent.com/40589172/88615141-e953ba00-d0c3-11ea-8d48-aa7a2b12d796.png)

**Comment by ske1996** [comment]
f2进bios，调成中文，然后关闭一切带有“安全”的东西，保存，退出
