### ISSUE TITLE
【经验/方案】关于ComboJack耳麦切换的问题

### ISSUE THREAD

**Issue by Tazlorkkenm** [ske1996/matebook-13-2019-oc-efi#23]
已经把VerbStub放入到OC的kexts里面了，但是按照步骤在终端输入安装指令后提示提示 no such file

**Comment by ske1996** [comment]
没有啥安装指令，有一个sh的脚本运行一下就好，你可以在我的库里直接下载，或者去我贴出来的原地址下载，sh脚本的运行方法:拖进终端，然后回车

**Comment by Tazlorkkenm** [comment]
非常感谢大佬，按照大佬的指示已经全部完成了，现在正在弄启动项，华为这个这个启动坑爹，用uefi把黑苹果放到第一个启动项重启之后windows的启动项又恢复成第一个了，然后在bios屏蔽了Windows的启动项，打算用OC里面的windows启动，结果这个oc进入的windows启动失败@@

**Comment by ske1996** [comment]
我做的efi只考虑引导macos，不考虑引导windows

**Comment by ske1996** [comment]
需要你用原生的uefi bootloader去引导windows

**Comment by Tazlorkkenm** [comment]
好的，谢谢大佬，我自己研究一下
