### ISSUE TITLE
最新8月6日发布的版本触摸板不能用

### ISSUE THREAD

**Issue by foreveryyl** [ske1996/matebook-13-2019-oc-efi#26]
最新8月6日发布的版本触摸板不能用

**Comment by foreveryyl** [comment]
matebook2019 i7-8565u mx150

**Comment by ske1996** [comment]
对的，是有点问题，有人跟我说了，你可以先用0728的

**Comment by ske1996** [comment]
去试试我刚更新的0811

**Comment by foreveryyl** [comment]
谢谢，马上试试




在2020年08月11日 17:28，ske1996 写道：

去试试我刚更新的0811

**Comment by foreveryyl** [comment]
可以了，谢谢大神，就是取消了usbinject.kext吗？




在2020年08月11日 17:29，foreveryyl 写道：
谢谢，马上试试




在2020年08月11日 17:28，ske1996 写道：

去试试我刚更新的0811

**Comment by ske1996** [comment]
不是，重写了一下config的结构，还有一个ssdt跟kext的调整

**Comment by foreveryyl** [comment]
很赞，现在唯一的遗憾就剩下摄像头和网卡不能aoirdrop了，看你在另一个回复里说有华硕的摄像头驱动在哪里下载，我试试




在2020年08月11日 21:33，ske1996 写道：

不是，重写了一下config的结构，还有一个ssdt跟kext的调整

**Comment by ske1996** [comment]
放弃吧，不是你想的那样，要是简单到复制进去就能用的话就轮不到你去试了
