### ISSUE TITLE
CPU变频是正常的吗？

### ISSUE THREAD

**Issue by zh98227** [ske1996/matebook-13-2019-oc-efi#27]
我用cpu-s测试出来的显示未睿频？
<img width="420" alt="706B7546-5A52-4B7B-84D3-B9000B4F9E9C" src="https://user-images.githubusercontent.com/25291472/90023215-0dc7ad00-dce6-11ea-9241-123aac3b86ba.png">

**Comment by ske1996** [comment]
我们都正常的啊，你用intel官方的那个软件自己看看

**Comment by ske1996** [comment]
Intel power gadget

**Comment by zh98227** [comment]
> Intel power gadget

似乎好像有些不正常 matebook13 i5版本 8 256。
<img width="400" alt="CE39D174-1F0C-4A26-B444-07DD7F7A6D26" src="https://user-images.githubusercontent.com/25291472/90030631-d9a4ba00-dcee-11ea-832b-450a0f6a71d9.png">

**Comment by ske1996** [comment]
你开压力测试了？

**Comment by zh98227** [comment]
> 你开压力测试了？

目测power，并没有跑满功耗，只是单纯频率高。

**Comment by ske1996** [comment]
哪个日期版本的efi？确定没动过任何里面的东西？

**Comment by zh98227** [comment]
> 哪个日期版本的efi？确定没动过任何里面的东西？
昨天更新的版本，我现在重启了一下电脑，似乎情况得到了缓解，刚开机频率稳定在2.6左右。

**Comment by ske1996** [comment]
重新做一下cpufriend吧

**Comment by zh98227** [comment]
> 重新做一下cpufriend吧

正常情况下开机频率应该在多少？

**Comment by ske1996** [comment]
我设置的1.8
