### ISSUE TITLE
提交一个关于使用感受方面的问题

### ISSUE THREAD

**Issue by zh98227** [ske1996/matebook-13-2019-oc-efi#29]
itlwm开机加载太慢了，以至于我上一次关机前的QQ，Telegram等都会显示网络连接失败而产生登陆失败。或许可以从加载kext的顺序，来入手解决此问题。

**Comment by ske1996** [comment]
不是我把他放最后的，我用的propertree的snapshot，我相信那个默认顺序是最好的，至于你出现的问题，你还真是第一个😂😂😂，你有试过改过顺序吗，有改善吗

**Comment by ske1996** [comment]
另外你能汇报下你的机型配置吗

**Comment by zh98227** [comment]
> 另外你能说下你的机型配置吗

可以，matebook 2019款，i5 8g 256g
<img width="586" alt="QQ20200815-200723@2x" src="https://user-images.githubusercontent.com/25291472/90311956-f9c4bb00-df32-11ea-8ce2-06946183b3a9.png">

**Comment by zh98227** [comment]
应该是我记错了，我是2018年买的，第一批matebook13。不确定是否是2019款

**Comment by ske1996** [comment]
所以是matebook什么呢？

**Comment by zh98227** [comment]
> 所以是matebook什么呢？

13

**Comment by ske1996** [comment]
你跟我说的那个你有试吗？结果如何？

**Comment by ske1996** [comment]
因为我群里加上我自己没有一个人有这个问题，而且用的snapshot做的顺序没有过什么错，你是有什么日志吗，还是你有什么根据，就是说是顺序的问题导致的？
