### ISSUE TITLE
2020款 matebook13  触摸板问题

### ISSUE THREAD

**Issue by 954739648** [ske1996/matebook-13-2019-oc-efi#30]
这位大佬你好，我来反馈其中一个比较影响使用的问题，就是2020款 的matebook13  触摸板还是有问题，也无法使用手势，开机那会还是有一点点反应的，不过鼠标箭头卡卡的，后来直接没反应了   大佬可否有时间做一份专属2020款的matebook13出来给我们这些小弟用呢

**Comment by 954739648** [comment]
再补充一下，系统版本是10.15.16的

**Comment by ske1996** [comment]
去看看重新做i2c相关的ssdt就好，具体的教程百度一下就有了
