### ISSUE TITLE
matebook14 2020款 cpu i5-10210U MX350。EFI替换为大佬制作，使用中遇到的问题

### ISSUE THREAD

**Issue by ILXIANG** [ske1996/matebook-13-2019-oc-efi#31]
1.HIDPI根据大佬提醒最高设置到了 1343x895 ，但睡眠唤醒后 屏幕会不亮（仔细观察发现有一点点光，并未有完全黑屏）。
2.电脑连接HDMI，外接显示器无反应。笔记本刚插上HDMI插口时，会卡顿一段时间。然后在系统偏好设置/显示器里检测不出显示器。
3.其他地方暂时没有发现异常。
4.大佬有时间的话麻烦回答下，是不是那里我没有设置正确（看到issue有人同样是2020款matebook14基本完美运行了）。
在此感谢ske1996大佬的维护！

**Comment by ske1996** [comment]
这个问题很玄学，因为有的人有的人没有，所以只能你自己在你自己的电脑上自己调试

1.这个唤醒问题能出的原因很多，远景搜一下"睡眠唤醒黑屏"

2.hdmi的问题，搜"缓冲帧"

**Comment by ske1996** [comment]
补充:设置hidpi的时候的第一步你选的那个注入edid吗

**Comment by ILXIANG** [comment]
> 这个问题很玄学,因为有的人有的人没有,所以只能你自己在你自己的电脑上自己调试
> 
> 1.这个唤醒问题能出的原因很多,远景搜一下"睡眠唤醒黑屏"
> 
> 2.hdmi]，["]"

**Comment by ILXIANG** [comment]
感谢解答,hidpi我用的是驱动开启的,应该没注入EDID

**Comment by ske1996** [comment]
> 感谢解答,hidpi我用的是驱动开启的,应该没注入EDID

我挺好奇的，你能告诉我是什么驱动吗🤣🤣🤣我还真不知道还有这个驱动呢
