### ISSUE TITLE
刚才提交的issue不晓得怎么没了,在邮箱里才看到回复

### ISSUE THREAD

**Issue by ILXIANG** [ske1996/matebook-13-2019-oc-efi#32]
hidpi以前是用 https://github.com/frezs  这位大佬分享的MateBook14-Hackintosh开启的.(复制 DisplayVendorID-dae 和 Icons.plist 到 /系统/资源库/Displays/Contents/Resources/Overrides/  然后使用DRM切换的分辨率)

**Comment by ske1996** [comment]
卧槽，这可够古老，按我写的重新弄一下hidpi，然后记得第一步注入edid

**Comment by ske1996** [comment]
你干脆按我写的重装都行

**Comment by ILXIANG** [comment]
嗯嗯好的.电脑在公司,明天我重装试下.感谢感谢
