### ISSUE TITLE
【可无问题运行】14“ 2019，i5 8265U, MX250，ACPI不完全加载, GFX0未完全禁用。

### ISSUE THREAD

**Issue by andrewlsa** [ske1996/matebook-13-2019-oc-efi#36]
非常感谢你的EFI，一切运行正常。

MaciASL显示

独显不完全屏蔽，初步推断dGPU-Off不完全匹配： 
// Firmware Error (ACPI): Could not resolve symbol [^GFX0.CLID], AE_NOT_FOUND (20200110/dswload-496)
// Firmware Error (ACPI): Could not resolve symbol [^GFX0.CLID], AE_NOT_FOUND (20200110/dswload2-477)
// Firmware Error (ACPI): Could not resolve symbol [^GFX0.CLID], AE_NOT_FOUND (20200110/dswload-496)
// Firmware Error (ACPI): Could not resolve symbol [^GFX0.CLID], AE_NOT_FOUND (20200110/dswload2-477)

External (_SB_.PCI0.GFX0, DeviceObj)
    External (_SB_.PCI0.GFX0.AINT, MethodObj)    // 2 Arguments
    External (_SB_.PCI0.GFX0.ALSI, UnknownObj)
    External (_SB_.PCI0.GFX0.CBLV, UnknownObj)
    External (_SB_.PCI0.GFX0.CDCK, UnknownObj)
    External (_SB_.PCI0.GFX0.CLID, UnknownObj)
    External (_SB_.PCI0.GFX0.DD1F, DeviceObj)
    External (_SB_.PCI0.GFX0.GLID, MethodObj)    // 1 Arguments
    External (_SB_.PCI0.GFX0.GSCI, MethodObj)    // 0 Arguments
    External (_SB_.PCI0.GFX0.GSSE, UnknownObj)
    External (_SB_.PCI0.GFX0.IUEH, MethodObj)    // 1 Arguments
    External (_SB_.PCI0.GFX0.STAT, UnknownObj)
    External (_SB_.PCI0.GFX0.TCHE, UnknownObj)

------------------------------------------------------------------
log show -- ”ACPI“发现以下错误

ACPI Error:
[_PR0]
Namespace lookup failure, AE_ALREADY_EXISTS
(20160930/dswload2-411)

Method parse/execution failed
[\_SB.PCI0] (Node ffffff86a5bee360)

2 table load failures, 23 successful

_STA, USTP错误
config里面不加载GPI0和TPD0的情况下，所有表加载成功。

**Comment by ske1996** [comment]
对，这个本就只是2019的13量身定做的，只是后来很多人去用后发现告诉我14也能用而已，没对14做特别的定制，看你提出了gpi0的问题，触控板不能用了吗？
