### ISSUE TITLE
matebook 13 2020 替换EFI后无法引导

### ISSUE THREAD

**Issue by liuyue0016** [ske1996/matebook-13-2019-oc-efi#39]
现在使用0.5.6引导，计划替换为此EFI以顺便升级到0.6.0.但是替换后无法引导。开机时无法进入OC引导界面，直接跳转到Windows开机但是Windows也无法开机。清除Nvram后重新建立引导路径，问题依然存在。
matebook 13 2020， i5-10210U，无独显。附件为现在用的EFI。
[OC-backup0821.zip](https://github.com/ske1996/matebook-13-2019-oc-efi/files/5118085/OC-backup0821.zip)

**Comment by ske1996** [comment]
Misc/boot/showpicker→false

然后进mac后，在设置/启动硬盘，设置成默认macos启动就好

不是我efi的问题

**Comment by liuyue0016** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    谢谢，问题已经解决了，不知道为什么不能在启动硬盘里面把MacOS自身设置为默认选项（显示Nvram设置不能完成更改），但是已经不影响使用了。另外群的二维码好像又失效了，能拉进群么..
    
    
    

    

    

    On 08/24/2020 20:11，ske1996<notifications@github.com> wrote： 



Closed #39.

**Comment by ske1996** [comment]
我测试了，没过期，你应该是没答对题

**Comment by liuyue0016** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    不是big sur包里面的哪个二维码么。。
    
        
            
        
    
    
    
    

    

    

    On 08/28/2020 13:49，ske1996<notifications@github.com> wrote： 




我测试了，没过期，你应该是没答对题

**Comment by ske1996** [comment]
不是，去好好从头读我的repo吧
