### ISSUE TITLE
matebook13 2019外置硬盘安装一切正常，但外置硬盘上oc引导失败

### ISSUE THREAD

**Issue by u2uuu** [ske1996/matebook-13-2019-oc-efi#4]
首先，感谢分享，黑苹果已成功装在了外置硬盘上，进得了系统。
但装好黑苹果后，外置硬盘的ESP分区是空的（没有BOOT、CLOVER或OC）。
用优盘的EFI（BOOT和CLOVER）可以正常引导
用“oc用的efi”里的BOOT和OC两个文件夹放进ESP分区，按照设置走了一遍，不得行
用了优盘的EFI里的BOOT文件夹和“oc用的efi”OC文件夹，搭配着用也不得行
（有点头大，外置硬盘的ESP分区该怎么配好）

**Comment by u2uuu** [comment]
忘了补充机子说明，matebook 13 2019版，i7-8565u，mx250，内部硬盘西数，外置硬盘铠侠

**Comment by ske1996** [comment]
1.　你确定外置硬盘ESP分区是空的？还是说外置硬盘没有ESP分区？
2.   有关OC的uefi引导的建立，使用easyuefi建立引导时应选择的文件路径为EFI/BOOT/bootx64.efi，这个与clover不同，clover是EFI/clover/cloverx64.efi，要注意
3.  引导使用外置硬盘引导不应按一般情况来考虑，尝试开机后F12进入自带bootloader后选择你的硬盘。
4.  考虑以下清空外置硬盘上的nvram后重建外置硬盘的uefi引导
5.  外置硬盘上nvram是否有建立？这个也很重要。
 

以上仅为分析，我不曾使用过外置硬盘引导黑苹果，而且因为东西不在我手边没法调试，所以很难说清楚

**Comment by u2uuu** [comment]
1.ESP分区是我安装黑苹果之前就分好的，把黑苹果装进外置硬盘后ESP分区已然是空的（用Diskgenies看过了），所以才会尝试把不同的BOOT放进ESP分区
2.因为ESP里没有BOOT文件夹，我尝试复制其他BOOT到外置硬盘上，比如用引导安装的优盘的BOOT（成功）和你给的“OC用EFI”里的BOOT（失败），笔记本自带的硬盘里的BOOT我还没复制进去尝试过
3.我的计划是，在不插入外置硬盘的时候，直接进入笔记本自带硬盘的Windows，在插入外置硬盘的时候，通过f12选择启动项进入外置硬盘的MacOS，目前通过安装引导用的CLOVER和BOOT可以实现，但我仍想用OC，所以在换成OC的时候遇到了麻烦
4和5.对不起，第一次接触黑苹果，我并不太清楚nvram是什么……

目前我已经用DiskGenies删除了原先的ESP分区然后重建了一遍，外置硬盘确定有ESP分区了，但这个分区是空的，没有EFI也没有bootx64.efi，就是纯空白

如果大佬也没办法的话我打算复制笔记本自带硬盘的BOOT进外置硬盘，然后再放入OC试试
【顺带一问，往ESP分区写入内容的时候，是把“/20200709更新oc用efi/EFI”整个拖进ESP分区呢，还是把“/20200709更新oc用efi/EFI/OC”拖进去呢】

**Comment by u2uuu** [comment]
![image](https://user-images.githubusercontent.com/51023864/87632899-e6280800-c76c-11ea-844f-8fa4f15fda1b.png)
如图，ESP分区空无一物

**Comment by ske1996** [comment]
第一，拖进efi的一整个文件夹，说白了就是你打开esp分区之后只看见一个efi文件夹就对了

第二，oc压缩包的efi中的boot文件夹与clover不通用，别瞎管

第三，我的oc压缩包解压完以后有efi文件夹，efi文件夹里面就有boot文件夹啊，你自己不会复制，不能说没有啊
