### ISSUE TITLE
Matebook 13 2018升级15.6后键盘快捷键失效

### ISSUE THREAD

**Issue by zljing-today** [ske1996/matebook-13-2019-oc-efi#40]
配置是: Matebook 13 2018款，I5 MX150 SN720
初次装好是10.15.5，用的是大佬的811的EFI，能用的驱动都正常，键盘快捷键也OK。
昨天晚上升级了15.6后发现键盘快捷键按了没反应。
试了最新的822的EFI依然没有解决，请大佬给点建议，谢谢。

**Comment by ske1996** [comment]
确实没遇到过，清空nvram试试吧

**Comment by ske1996** [comment]
如果不行，那就或者你换换我release里面的别的efi试试

**Comment by zljing-today** [comment]
哈哈，我乌龙了，原来是因为升级过程中我无意间按到了Fn键。
