### ISSUE TITLE
我的机器是2018款13，目前存在Wi-Fi连接路由器变成en1，无法上网，连接手机热点为en0，上网正常

### ISSUE THREAD

**Issue by 7UGef74eY1bdQfsYqpdV591E81** [ske1996/matebook-13-2019-oc-efi#42]
另外一个是光感驱动没有，请提供一下，以上两个问题便是我所遇到的问题，别的目前基本上不影响也不重要了，请问这两个问题如何解决

**Comment by ske1996** [comment]
Wifi的问题我不是开发者，请于itlwm的下面留言，光感驱动我有更新0822的那个，有放进去
