### ISSUE TITLE
【已解决】2020版matebook i5 安装界面触摸板无法使用

### ISSUE THREAD

**Issue by re-doc** [ske1996/matebook-13-2019-oc-efi#44]
型号klvc-wxx9，安装到抹掉磁盘的界面，触摸板无法使用，有线鼠标也无法使用

**Comment by ske1996** [comment]
啥机器啊

你这个格式告诉我

Matebookxx 20xx ix

**Comment by re-doc** [comment]
> 啥机器啊
> 
> 你这个格式告诉我
> 
> Matebookxx 20xx ix
huawei matebook 14 2020
 处理器              英特尔 Core i5-10210U @ 1.60GHz 四核
  主板                华为 KLVC-WXX9-PCB ( I/O - 0284 for Intel 400 Series 芯片组 Family On-Package Platform Controller Hub )
  显卡                Nvidia GeForce MX350 ( 2 GB )
  内存                16 GB ( SK Hynix LPDDR3 2133MHz )
  主硬盘              西数 WDC PC SN730 SDBPNTY-512G-1027 ( 512 GB / 固态硬盘 )
  显示器              奇美 CMN8C02 P140ZKA-BZ1 ( 14 英寸  )
  声卡                瑞昱 High Definition Audio @ 英特尔 英特尔智音技术音频控制器
  网卡                英特尔 Wireless-AC 9560 160MHz

**Comment by ske1996** [comment]
1.用oc安装，直接在硬盘efi分区扩容后放进我oc的efi，然后用oc引导安装盘，具体教程自行百度

2.删除u盘中的efi/clover/kexts/other/usbinjectall.kext
