### ISSUE TITLE
【经验】matebook13 2019触摸板无法使用

### ISSUE THREAD

**Issue by yliuhz** [ske1996/matebook-13-2019-oc-efi#45]
如题，按照教程一步一步来的，但触摸板一直无法使用（指的是完全无法使用），不知道有没有和我一样情况的。

**Comment by ske1996** [comment]
没遇到过，你是不是设置了插上鼠标后禁用触控板或者是碰到了f10/f11/f12其中一个键开启了禁用触控板？

截图你的设置/触控板

**Comment by ske1996** [comment]
对了，你用的哪一版的efi

**Comment by yliuhz** [comment]
<img width="647" alt="截屏2020-09-07 上午2 26 00" src="https://user-images.githubusercontent.com/61338146/92372365-acf77e80-f0b1-11ea-9d04-ad1d72a1ad75.png">

**Comment by yliuhz** [comment]
用的是现在仓库里的oc

**Comment by ske1996** [comment]
因为我自己用着确实好好的，你试试我说的那几项排查一下，那几个快捷键按一按，因为你的电脑识别出来了触控板了，说明驱动上了

**Comment by yliuhz** [comment]
我试了拔掉鼠标 还有按那几个键。但都不行

**Comment by yliuhz** [comment]
好的，先谢谢你

**Comment by ske1996** [comment]
不行的话就清空一下nvram，再不行就去我的release里翻一下0814的，用一下那个试试

**Comment by ske1996** [comment]
最后问一句，你确定你不是2020的吗

**Comment by yliuhz** [comment]
2019滴，i5 8565的

**Comment by ske1996** [comment]
清空一下nvram，再不行就去我的release里翻一下0814的，用一下那个试试
因为自0814的之后我删除了一些跟触摸板有关的东西，而且我没亲自上手你的电脑，所以只能做这么多

你也可以下载一下geni2c这个软件检查一下你的i2c加载问题

**Comment by yliuhz** [comment]
反馈：清空之后就好了，谢谢🐻dei

**Comment by hesongtao96** [comment]
我是用sudo kextcache -i /  清空缓存解决的，供参考

**Comment by 894722197** [comment]
触控板已经驱动好了，但是手指滑动触控板区域就是没反应，您遇到过么

**Comment by hesongtao96** [comment]
> 触控板已经驱动好了，但是手指滑动触控板区域就是没反应，您遇到过么

前一阵子确实经常遇到触控板没反应，甚至还需要重启好多次才能解决。后来，我把win10的快速启动关闭，这种情况就少了很多，但还是偶尔会出现。
