### ISSUE TITLE
matebook13 2018版成功上车以及两个问题

### ISSUE THREAD

**Issue by mokkawiish** [ske1996/matebook-13-2019-oc-efi#46]
机型matebook13 i5-8265u sn720
系统10.15.6
引导OC0.6.0
已经按照ske的教程，全部调整完毕，感谢您的贡献！
不可用：指纹、摄像头、独显
新问题：
1.麦克风收音有问题，只有杂音，完全不可用
2.WIFI识别为以太网，随航、airdrop不可用
以上两个问题不知是否为个人设置或硬件型号不一样导致。

**Comment by mokkawiish** [comment]
最新版彩蛋不错，炸到我了!)

**Comment by ske1996** [comment]
麦克风收音问题我确认没有遇到过，你是装了combojeck的脚本后出现的吗

Airdrop没法用，因为走的以太网接口，这个是常识

**Comment by mokkawiish** [comment]
> 麦克风收音问题我确认没有遇到过，你是装了combojeck的脚本后出现的吗
> 
> Airdrop没法用，因为走的以太网接口，这个是常识

麦克风跟脚本没关系。状况为录音机录音只有类似白噪音，收不到人声；siri不可用。

**Comment by ske1996** [comment]
我的意思是你是装了脚本后出现的吗
你这个回答意思就是【不是】对吧

**Comment by ske1996** [comment]
windows下麦克风正常吗，如果windows下麦克风正常确定没有坏的话，就重置下nvram试一下
