### ISSUE TITLE
matebook 14 2020 hdmi黑屏解决0905

### ISSUE THREAD

**Issue by 378210331** [ske1996/matebook-13-2019-oc-efi#49]
反馈:使用0905版本的OC,进入10.15.6系统后显卡显示仿冒为RTX3090,连接HDMI卡顿，外接显示器并无信号。其他功能正常。
缓存帧修改教程没找到合适的。之后比较其他人的EFI。使用vs code 修改config.plist,搜索“<key>PciRoot(0x0)/Pci(0x2,0x0)</key>” ，将下方的<dict> 标签修改为下文，仿冒Intel Iris Plus Graphics 655 能正常驱动hdmi,希望只是个例。不知道显卡性能如何。
`<dict>
				<key>AAPL,ig-platform-id</key>
				<data>CQCbPg==</data>
				<key>AAPL,slot-name</key>
				<string>Internal@0,2,0</string>
				<key>device-id</key>
				<data>mz4AAA==</data>
				<key>device_type</key>
				<string>VGA compatible controller</string>
				<key>disable-external-gpu</key>
				<data>AQAAAA==</data>
				<key>enable-hdmi-dividers-fix</key>
				<data>AQAAAA==</data>
				<key>enable-hdmi20</key>
				<data>AQAAAA==</data>
				<key>enable-lspcon-support</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con0-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con0-pipe</key>
				<data>EgAAAA==</data>
				<key>framebuffer-con1-busid</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con1-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con1-has-lspcon</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con1-pipe</key>
				<data>EgAAAA==</data>
				<key>framebuffer-con1-preferred-lspcon-mode</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con1-type</key>
				<data>AAgAAA==</data>
				<key>framebuffer-con2-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con2-index</key>
				<data>/////w==</data>
				<key>framebuffer-con2-pipe</key>
				<data>EgAAAA==</data>
				<key>framebuffer-con2-type</key>
				<data>AAgAAA==</data>
				<key>framebuffer-flags</key>
				<data>DxvzAA==</data>
				<key>framebuffer-patch-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-portcount</key>
				<data>AgAAAA==</data>
				<key>framebuffer-stolenmem</key>
				<data>AADgAQ==</data>
				<key>framebuffer-unifiedmem</key>
				<data>AAAAgA==</data>
				<key>model</key>
				<string>Intel Iris Plus Graphics 655</string>
			</dict>
`

**Comment by ske1996** [comment]
对于14 2020来说你这个缓冲帧是对的，打的655，我的efi是以13做的，所以缓冲帧打的630，那个rtx3090是随便改的名字，啥也不影响，你要是喜欢也可以参照着改了

**Comment by shenhfhep** [comment]
> 反馈:使用0905版本的OC,进入10.15.6系统后显卡显示仿冒为RTX3090,连接HDMI卡顿，外接显示器并无信号。其他功能正常。
> 缓存帧修改教程没找到合适的。之后比较其他人的EFI。使用vs code 修改config.plist,搜索“PciRoot(0x0)/Pci(0x2,0x0)” ，将下方的 标签修改为下文，仿冒Intel Iris Plus Graphics 655 能正常驱动hdmi,希望只是个例。不知道显卡性能如何。
> `<dict> <key>AAPL,ig-platform-id</key> <data>CQCbPg==</data> <key>AAPL,slot-name</key> <string>Internal@0,2,0</string> <key>device-id</key> <data>mz4AAA==</data> <key>device_type</key> <string>VGA compatible controller</string> <key>disable-external-gpu</key> <data>AQAAAA==</data> <key>enable-hdmi-dividers-fix</key> <data>AQAAAA==</data> <key>enable-hdmi20</key> <data>AQAAAA==</data> <key>enable-lspcon-support</key> <data>AQAAAA==</data> <key>framebuffer-con0-enable</key> <data>AQAAAA==</data> <key>framebuffer-con0-pipe</key> <data>EgAAAA==</data> <key>framebuffer-con1-busid</key> <data>AQAAAA==</data> <key>framebuffer-con1-enable</key> <data>AQAAAA==</data> <key>framebuffer-con1-has-lspcon</key> <data>AQAAAA==</data> <key>framebuffer-con1-pipe</key> <data>EgAAAA==</data> <key>framebuffer-con1-preferred-lspcon-mode</key> <data>AQAAAA==</data> <key>framebuffer-con1-type</key> <data>AAgAAA==</data> <key>framebuffer-con2-enable</key> <data>AQAAAA==</data> <key>framebuffer-con2-index</key> <data>/////w==</data> <key>framebuffer-con2-pipe</key> <data>EgAAAA==</data> <key>framebuffer-con2-type</key> <data>AAgAAA==</data> <key>framebuffer-flags</key> <data>DxvzAA==</data> <key>framebuffer-patch-enable</key> <data>AQAAAA==</data> <key>framebuffer-portcount</key> <data>AgAAAA==</data> <key>framebuffer-stolenmem</key> <data>AADgAQ==</data> <key>framebuffer-unifiedmem</key> <data>AAAAgA==</data> <key>model</key> <string>Intel Iris Plus Graphics 655</string> </dict> `

matebook14 2019款hdmi也有这个问题,请问老哥你是修改了OC文件夹下的config.plist吗

**Comment by 378210331** [comment]
> > 反馈:使用0905版本的OC,进入10.15.6系统后显卡显示仿冒为RTX3090,连接HDMI卡顿，外接显示器并无信号。其他功能正常。
> > 缓存帧修改教程没找到合适的。之后比较其他人的EFI。使用vs code 修改config.plist,搜索“PciRoot(0x0)/Pci(0x2,0x0)” ，将下方的 标签修改为下文，仿冒Intel Iris Plus Graphics 655 能正常驱动hdmi,希望只是个例。不知道显卡性能如何。
> > `<dict> <key>AAPL,ig-platform-id</key> <data>CQCbPg==</data> <key>AAPL,slot-name</key> <string>Internal@0,2,0</string> <key>device-id</key> <data>mz4AAA==</data> <key>device_type</key> <string>VGA compatible controller</string> <key>disable-external-gpu</key> <data>AQAAAA==</data> <key>enable-hdmi-dividers-fix</key> <data>AQAAAA==</data> <key>enable-hdmi20</key> <data>AQAAAA==</data> <key>enable-lspcon-support</key> <data>AQAAAA==</data> <key>framebuffer-con0-enable</key> <data>AQAAAA==</data> <key>framebuffer-con0-pipe</key> <data>EgAAAA==</data> <key>framebuffer-con1-busid</key> <data>AQAAAA==</data> <key>framebuffer-con1-enable</key> <data>AQAAAA==</data> <key>framebuffer-con1-has-lspcon</key> <data>AQAAAA==</data> <key>framebuffer-con1-pipe</key> <data>EgAAAA==</data> <key>framebuffer-con1-preferred-lspcon-mode</key> <data>AQAAAA==</data> <key>framebuffer-con1-type</key> <data>AAgAAA==</data> <key>framebuffer-con2-enable</key> <data>AQAAAA==</data> <key>framebuffer-con2-index</key> <data>/////w==</data> <key>framebuffer-con2-pipe</key> <data>EgAAAA==</data> <key>framebuffer-con2-type</key> <data>AAgAAA==</data> <key>framebuffer-flags</key> <data>DxvzAA==</data> <key>framebuffer-patch-enable</key> <data>AQAAAA==</data> <key>framebuffer-portcount</key> <data>AgAAAA==</data> <key>framebuffer-stolenmem</key> <data>AADgAQ==</data> <key>framebuffer-unifiedmem</key> <data>AAAAgA==</data> <key>model</key> <string>Intel Iris Plus Graphics 655</string> </dict> `
> 
> matebook14 2019款hdmi也有这个问题,请问老哥你是修改了OC文件夹下的config.plist吗

用hacktool 可以打缓存帧修改仿冒核显解决，然后添加到config.plist里面，我上面那串是直接复制其他的EFI替换的，2020用的UHD620可以成功驱动HDMI

**Comment by shenhfhep** [comment]
> > > 反馈:使用0905版本的OC,进入10.15.6系统后显卡显示仿冒为RTX3090,连接HDMI卡顿，外接显示器并无信号。其他功能正常。
> > > 缓存帧修改教程没找到合适的。之后比较其他人的EFI。使用vs code 修改config.plist,搜索“PciRoot(0x0)/Pci(0x2,0x0)” ，将下方的 标签修改为下文，仿冒Intel Iris Plus Graphics 655 能正常驱动hdmi,希望只是个例。不知道显卡性能如何。
> > > `<dict> <key>AAPL,ig-platform-id</key> <data>CQCbPg==</data> <key>AAPL,slot-name</key> <string>Internal@0,2,0</string> <key>device-id</key> <data>mz4AAA==</data> <key>device_type</key> <string>VGA compatible controller</string> <key>disable-external-gpu</key> <data>AQAAAA==</data> <key>enable-hdmi-dividers-fix</key> <data>AQAAAA==</data> <key>enable-hdmi20</key> <data>AQAAAA==</data> <key>enable-lspcon-support</key> <data>AQAAAA==</data> <key>framebuffer-con0-enable</key> <data>AQAAAA==</data> <key>framebuffer-con0-pipe</key> <data>EgAAAA==</data> <key>framebuffer-con1-busid</key> <data>AQAAAA==</data> <key>framebuffer-con1-enable</key> <data>AQAAAA==</data> <key>framebuffer-con1-has-lspcon</key> <data>AQAAAA==</data> <key>framebuffer-con1-pipe</key> <data>EgAAAA==</data> <key>framebuffer-con1-preferred-lspcon-mode</key> <data>AQAAAA==</data> <key>framebuffer-con1-type</key> <data>AAgAAA==</data> <key>framebuffer-con2-enable</key> <data>AQAAAA==</data> <key>framebuffer-con2-index</key> <data>/////w==</data> <key>framebuffer-con2-pipe</key> <data>EgAAAA==</data> <key>framebuffer-con2-type</key> <data>AAgAAA==</data> <key>framebuffer-flags</key> <data>DxvzAA==</data> <key>framebuffer-patch-enable</key> <data>AQAAAA==</data> <key>framebuffer-portcount</key> <data>AgAAAA==</data> <key>framebuffer-stolenmem</key> <data>AADgAQ==</data> <key>framebuffer-unifiedmem</key> <data>AAAAgA==</data> <key>model</key> <string>Intel Iris Plus Graphics 655</string> </dict> `
> > 
> > 
> > matebook14 2019款hdmi也有这个问题,请问老哥你是修改了OC文件夹下的config.plist吗
> 
> 用hacktool 可以打缓存帧修改仿冒核显解决，然后添加到config.plist里面，我上面那串是直接复制其他的EFI替换的，2020用的UHD620可以成功驱动HDMI

老哥,可否说的详细一点,我看了2019款核显型号也是hd620,是不是可以直接用你的?可以给我一份吗,多谢

**Comment by 378210331** [comment]
> > > > 反馈:使用0905版本的OC,进入10.15.6系统后显卡显示仿冒为RTX3090,连接HDMI卡顿，外接显示器并无信号。其他功能正常。
> > > > 缓存帧修改教程没找到合适的。之后比较其他人的EFI。使用vs code 修改config.plist,搜索“PciRoot(0x0)/Pci(0x2,0x0)” ，将下方的 标签修改为下文，仿冒Intel Iris Plus Graphics 655 能正常驱动hdmi,希望只是个例。不知道显卡性能如何。
> > > > `<dict> <key>AAPL,ig-platform-id</key> <data>CQCbPg==</data> <key>AAPL,slot-name</key> <string>Internal@0,2,0</string> <key>device-id</key> <data>mz4AAA==</data> <key>device_type</key> <string>VGA compatible controller</string> <key>disable-external-gpu</key> <data>AQAAAA==</data> <key>enable-hdmi-dividers-fix</key> <data>AQAAAA==</data> <key>enable-hdmi20</key> <data>AQAAAA==</data> <key>enable-lspcon-support</key> <data>AQAAAA==</data> <key>framebuffer-con0-enable</key> <data>AQAAAA==</data> <key>framebuffer-con0-pipe</key> <data>EgAAAA==</data> <key>framebuffer-con1-busid</key> <data>AQAAAA==</data> <key>framebuffer-con1-enable</key> <data>AQAAAA==</data> <key>framebuffer-con1-has-lspcon</key> <data>AQAAAA==</data> <key>framebuffer-con1-pipe</key> <data>EgAAAA==</data> <key>framebuffer-con1-preferred-lspcon-mode</key> <data>AQAAAA==</data> <key>framebuffer-con1-type</key> <data>AAgAAA==</data> <key>framebuffer-con2-enable</key> <data>AQAAAA==</data> <key>framebuffer-con2-index</key> <data>/////w==</data> <key>framebuffer-con2-pipe</key> <data>EgAAAA==</data> <key>framebuffer-con2-type</key> <data>AAgAAA==</data> <key>framebuffer-flags</key> <data>DxvzAA==</data> <key>framebuffer-patch-enable</key> <data>AQAAAA==</data> <key>framebuffer-portcount</key> <data>AgAAAA==</data> <key>framebuffer-stolenmem</key> <data>AADgAQ==</data> <key>framebuffer-unifiedmem</key> <data>AAAAgA==</data> <key>model</key> <string>Intel Iris Plus Graphics 655</string> </dict> `
> > > 
> > > 
> > > matebook14 2019款hdmi也有这个问题,请问老哥你是修改了OC文件夹下的config.plist吗
> > 
> > 
> > 用hacktool 可以打缓存帧修改仿冒核显解决，然后添加到config.plist里面，我上面那串是直接复制其他的EFI替换的，2020用的UHD620可以成功驱动HDMI
> 
> 老哥,可否说的详细一点,我看了2019款核显型号也是hd620,是不是可以直接用你的?可以给我一份吗,多谢

直接可以用，用工具打开config.plist,替换对应下方的<dict>标签里面的内容为上面的重启看看。

**Comment by shenhfhep** [comment]
> config.plist



> > > > > 反馈:使用0905版本的OC,进入10.15.6系统后显卡显示仿冒为RTX3090,连接HDMI卡顿，外接显示器并无信号。其他功能正常。
> > > > > 缓存帧修改教程没找到合适的。之后比较其他人的EFI。使用vs code 修改config.plist,搜索“PciRoot(0x0)/Pci(0x2,0x0)” ，将下方的 标签修改为下文，仿冒Intel Iris Plus Graphics 655 能正常驱动hdmi,希望只是个例。不知道显卡性能如何。
> > > > > `<dict> <key>AAPL,ig-platform-id</key> <data>CQCbPg==</data> <key>AAPL,slot-name</key> <string>Internal@0,2,0</string> <key>device-id</key> <data>mz4AAA==</data> <key>device_type</key> <string>VGA compatible controller</string> <key>disable-external-gpu</key> <data>AQAAAA==</data> <key>enable-hdmi-dividers-fix</key> <data>AQAAAA==</data> <key>enable-hdmi20</key> <data>AQAAAA==</data> <key>enable-lspcon-support</key> <data>AQAAAA==</data> <key>framebuffer-con0-enable</key> <data>AQAAAA==</data> <key>framebuffer-con0-pipe</key> <data>EgAAAA==</data> <key>framebuffer-con1-busid</key> <data>AQAAAA==</data> <key>framebuffer-con1-enable</key> <data>AQAAAA==</data> <key>framebuffer-con1-has-lspcon</key> <data>AQAAAA==</data> <key>framebuffer-con1-pipe</key> <data>EgAAAA==</data> <key>framebuffer-con1-preferred-lspcon-mode</key> <data>AQAAAA==</data> <key>framebuffer-con1-type</key> <data>AAgAAA==</data> <key>framebuffer-con2-enable</key> <data>AQAAAA==</data> <key>framebuffer-con2-index</key> <data>/////w==</data> <key>framebuffer-con2-pipe</key> <data>EgAAAA==</data> <key>framebuffer-con2-type</key> <data>AAgAAA==</data> <key>framebuffer-flags</key> <data>DxvzAA==</data> <key>framebuffer-patch-enable</key> <data>AQAAAA==</data> <key>framebuffer-portcount</key> <data>AgAAAA==</data> <key>framebuffer-stolenmem</key> <data>AADgAQ==</data> <key>framebuffer-unifiedmem</key> <data>AAAAgA==</data> <key>model</key> <string>Intel Iris Plus Graphics 655</string> </dict> `
> > > > 
> > > > 
> > > > matebook14 2019款hdmi也有这个问题,请问老哥你是修改了OC文件夹下的config.plist吗
> > > 
> > > 
> > > 用hacktool 可以打缓存帧修改仿冒核显解决，然后添加到config.plist里面，我上面那串是直接复制其他的EFI替换的，2020用的UHD620可以成功驱动HDMI
> > 
> > 
> > 老哥,可否说的详细一点,我看了2019款核显型号也是hd620,是不是可以直接用你的?可以给我一份吗,多谢
> 
> 直接可以用，用工具打开config.plist,替换对应下方的标签里面的内容为上面的重启看看。

请问改的是哪个位置的config.plist, (小白问的比较多,见谅), 多谢

**Comment by PIndividual** [comment]
求大佬，能不能发下你的config……
你写的代码我替换进去都是单行的，不能用啊……
