### ISSUE TITLE
【解决方案】BigSur OC引导选项问题

### ISSUE THREAD

**Issue by shenhfhep** [ske1996/matebook-13-2019-oc-efi#51]
OC引导界面直接启动Mac的引导不见了,只剩下preboot可以进mac.请问怎样可以恢复
![257fe4b14de5c8f68a0900700edc1d6](https://user-images.githubusercontent.com/59674594/92843861-cbde7380-f417-11ea-9c6a-e3b3d531b64f.jpg)

**Comment by ske1996** [comment]
这是对的啊，bigsur都这样

**Comment by ske1996** [comment]
装个intel power gadget就好了

**Comment by shenhfhep** [comment]
> 装个intel power gadget就好了

在mac里装吗?多谢!

**Comment by shenhfhep** [comment]
> 装个intel power gadget就好了

OK,好了多谢
