### ISSUE TITLE
【经验】win10启动蓝屏

### ISSUE THREAD

**Issue by xuewolf417** [ske1996/matebook-13-2019-oc-efi#52]
oc菜单选择Windows启动蓝屏，无法进入系统

**Comment by Kong-888** [comment]
开机F12键选WIN 引导进入

**Comment by ske1996** [comment]
我没有在oc对windows做配适，我觉得没必要，就跟楼上这个哥们说的一样，开机F12选windows就好了

**Comment by xuewolf417** [comment]
问题关闭吧,我个人使用mod版本的oc来实现启动不蓝屏的，但是F12也是一个方法

**Comment by ske1996** [comment]
其实没必要，直接showpicker关了以后开机自动进系统就好，有切换需求再去用f12切换就完了。没必要每次都去看切换界面的

**Comment by shenhfhep** [comment]
> 其实没必要，直接showpicker关了以后开机自动进系统就好，有切换需求再去用f12切换就完了。没必要每次都去看切换界面的

请问showpiker怎么关闭？

**Comment by tonylemon** [comment]
OC    怎么调整默认启动win10系统？  按F12再选择进入MACOS

**Comment by ske1996** [comment]
Win下用easyuefi把win的引导提到最前面就行，这个不是说oc默认引导win，是自带的uefi的顺序的更改
