### ISSUE TITLE
HDMI输出蓝屏或者黑屏

### ISSUE THREAD

**Issue by xuewolf417** [ske1996/matebook-13-2019-oc-efi#54]
Matebook 2018款，用扩展坞输出HDMI不是蓝屏就是黑屏，不能正常外接显示

**Comment by ske1996** [comment]
很奇怪，根据我的测试情况不是这样的，你是18款的什么？还有就是你的外接用的线材还有屏幕是否有问题也要检查，单纯这么说而且我没有亲手去调试，很难解决问题
