### ISSUE TITLE
重新提交问题！关于HDMI输出蓝屏或者黑屏

### ISSUE THREAD

**Issue by xuewolf417** [ske1996/matebook-13-2019-oc-efi#55]
型号是：Matebook 13 2018款
i5 8265U 8G 512 MX150这款
系统安装的是：10.15.6
问题：Typec用适配器（试过多个，包括华为原装的），HDMI链接后，外接显示器蓝屏或者黑屏，但是系统能识别到显示器，同样的适配器，线材，显示器在windows10下一切正常
另外，华为适配器除了HDMI接口外还有VGA接口，用VGA接口输出就一切正常
以上，如果需要什么其他信息，我可以再补充

**Comment by ske1996** [comment]
配适器什么意思？充电器？扩展坞？你试试换个扩展坞，或者直接使用支持白苹果的typec转hdmi试试，主要是我们自己测试过，确实能用，你这个真的很奇怪

**Comment by xuewolf417** [comment]
适配器就是扩展坞，没说清楚，但是已经换了多个扩展坞了

**Comment by ske1996** [comment]
试试我说的那个支持mac的typec直转hdmi的这个线，看看是否能解决，其他的不知道该怎么办了，因为我们这边的测试情况是好的，缓冲帧的设置也是对的

**Comment by ske1996** [comment]
就是不要用扩展坞，用一头是typec一头是hdmi的那种

**Comment by xuewolf417** [comment]
目前一头是typec一头是DP接口也是如此

**Comment by ske1996** [comment]
DP的那个应该是没有的，因为缓冲帧里设置了dp转hdmi

**Comment by ske1996** [comment]
这个问题妥妥的是缓冲帧的问题，如果在你的机器上出问题了，你可以试试重新做缓冲帧，具体教程可以百度，但是可以保证的是，在我这边的机器的测试上是没问题的，所以之前跟你说的也都只是想想办法，因为具体原因不明
