### ISSUE TITLE
matebook 2019（8265U） HDMI口插上显示器没反应，电脑变得卡顿

### ISSUE THREAD

**Issue by shenhfhep** [ske1996/matebook-13-2019-oc-efi#56]
用了图上这个老哥的方法可以驱动，请问这样改会不会影响性能？
<img width="1269" alt="截屏2020-09-16 上午11 57 30" src="https://user-images.githubusercontent.com/59674594/93290852-404c5480-f814-11ea-9c2b-3ebdf9c851eb.png">

**Comment by ske1996** [comment]
你是13还是14说清楚
