### ISSUE TITLE
matebook14 2019（8265U） HDMI口插上显示器没反应，电脑变得卡顿

### ISSUE THREAD

**Issue by shenhfhep** [ske1996/matebook-13-2019-oc-efi#57]
用了图上这个老哥的方法可以驱动，请问这样改会不会影响性能？
<img width="1269" alt="截屏2020-09-16 上午11 57 30" src="https://user-images.githubusercontent.com/59674594/93291219-10518100-f815-11ea-9741-253d12d978c3.png">

**Comment by ske1996** [comment]
不要重复提交issue，关闭了也可以继续留言的

**Comment by ske1996** [comment]
你是13还是14，说清楚

**Comment by shenhfhep** [comment]
> 你是13还是14，说清楚

14啊,,重新提交的时候写了14了

**Comment by ske1996** [comment]
我的efi是根据13做的，只是恰好可以通用 14能用一用而已，缓冲帧没有对 14进行优化因此你没法用hdmi，那个老哥给出的是适合14的缓冲帧，直接改就完了

**Comment by shenhfhep** [comment]
> 我的efi是根据13做的，只是恰好可以通用 14能用一用而已，缓冲帧没有对 14进行优化因此你没法用hdmi，那个老哥给出的是适合14的缓冲帧，直接改就完了

好的,多谢了

**Comment by shenhfhep** [comment]
> 我的efi是根据13做的，只是恰好可以通用 14能用一用而已，缓冲帧没有对 14进行优化因此你没法用hdmi，那个老哥给出的是适合14的缓冲帧，直接改就完了

用了这个缓冲帧之后HIDPI就用不了了。。。。

**Comment by ske1996** [comment]
那就试试重新开吧，我也确实手上没14的机器，也没法测试什么

**Comment by shenhfhep** [comment]
> 那就试试重新开吧，我也确实手上没14的机器，也没法测试什么

试了，暂时先放弃HDMI了。

**Comment by 378210331** [comment]
> > 那就试试重新开吧，我也确实手上没14的机器，也没法测试什么
> 
> 试了，暂时先放弃HDMI了。

用上面我的那个缓存帧，重新使用hdpi脚本开启就支持了，上面的缓存帧会覆盖原来的hdpi的设置，

**Comment by shenhfhep** [comment]
> > > 那就试试重新开吧，我也确实手上没14的机器，也没法测试什么
> > 
> > 
> > 试了，暂时先放弃HDMI了。
> 
> 用上面我的那个缓存帧，重新使用hdpi脚本开启就支持了，上面的缓存帧会覆盖原来的hdpi的设置，

老哥，你用的Catalina吗，我用bigsur重新用hidpi脚本没用
