### ISSUE TITLE
No Audio on Matebook13 2019 with latest 20200916

### ISSUE THREAD

**Issue by risidoro81** [ske1996/matebook-13-2019-oc-efi#58]
Hi, I just updated to latest rel. 20200916 and I have no more an audio device installed/detected. So, NO audio.
Before, with release from 6th of August, audio was working OK.
No changes to config.plist (except to disable the picker).

My system: 
Matebook13 2019 i7 mx150
Catalina 10.15.6
CFG Lock disabled

How can I extract some more debug info?

Thanks and keep up the wonderful work you're doing! Thanks, big time.

Isidoro

**Comment by risidoro81** [comment]
Sorry, it looks like I may have downloaded an incomplete release (or did you reupload it?) Anyway, I was missing two kext in my /kext and config.plist: FakePCIID_Intel_HDMI_Audio.kext and FakePCIID.kext

I have downloaded the 20200916 rel and now all it's working.

Thanks!!!

**Comment by ske1996** [comment]
yes,i reuploaded it
