### ISSUE TITLE
【未解决】MateBook 13 2020 i5 SSD: 三星 PM981

### ISSUE THREAD

**Issue by lvweixin** [ske1996/matebook-13-2019-oc-efi#61]
按照教程第一次启动后进入磁盘管理，但无法格式化Mac对应分区，提示空间不够，但实际分配了100G，求助大神啊，三星这个SSD该如何安装啊

**Comment by ske1996** [comment]
三星的需要用恢复法安装，但是还是建议你换一个硬盘吧，时不时的系统崩溃你受不了的

**Comment by lvweixin** [comment]
正在尝试把ssd的补丁加入OC中安装，进度条超级慢（但没死），观察下后续效果
