### ISSUE TITLE
sleep 和 蓝屏

### ISSUE THREAD

**Issue by ammi3** [ske1996/matebook-13-2019-oc-efi#65]
1：睡眠之后唤醒，界面缩放了，周围一圈黑色的
2：OC引导，进入Windows蓝屏。遇到问题。包括F12引导也是这个样子
19款i5 mnatebook14

**Comment by ske1996** [comment]
唤醒问题我说过了，去读hidpi那节

不要用oc引导windows，直接oc里设置mac为默认引导磁盘，关闭config里，showpicker

引导windows用f12选windows

**Comment by ske1996** [comment]
你在pe里重连一下win的引导

**Comment by ammi3** [comment]
> 唤醒问题我说过了，去读hidpi那节
> 
> 不要用oc引导windows，直接oc里设置mac为默认引导磁盘，关闭config里，showpicker
> 
> 引导windows用f12选windows
> 用pe重建
好的，已经好了，谢谢大哥，我之前看的不仔细！
