### ISSUE TITLE
怎么让它启动过程中不跑代码谢谢

### ISSUE THREAD

**Issue by foreveryyl** [ske1996/matebook-13-2019-oc-efi#68]
怎么让它启动过程中不跑代码谢谢 
<img width="784" alt="截屏2020-09-28 下午8 48 41" src="https://user-images.githubusercontent.com/9371263/94434272-1740a200-01cc-11eb-99b4-7bf9dc0d5af9.png">

**Comment by zy21802** [comment]
同求。跑码有点难看

**Comment by 378210331** [comment]
把config.plist 上搜索 “-v” 字符删除可以不跑码。
用opencore configurator 打开 config.plist，在Misc-其他设置 -> show picker 选项去掉勾选可以不进入oc引导界面。这样开机就和白苹果一致了。

**Comment by zy21802** [comment]
NVRAM下的7C...那里的-v删除了，还是跑码。在网上搜说是好像黑果小兵的比较麻烦？

**Comment by ske1996** [comment]
清空一遍nvram

**Comment by foreveryyl** [comment]
谢谢，可以了




在2020年09月29日 11:11，ske1996 写道：

清空一遍nvram

**Comment by zwgogogo** [comment]
> 谢谢，可以了 在2020年09月29日 11:11，ske1996 写道： 清空一遍nvram — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问怎么解决的，我这弄不好

**Comment by foreveryyl** [comment]
先把那个 -v删掉




在2020年10月02日 21:35，zwgogogo 写道：

谢谢，可以了 在2020年09月29日 11:11，ske1996 写道： 清空一遍nvram — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问怎么解决的，我这弄不好

**Comment by zwgogogo** [comment]
> 先把那个 -v删掉 在2020年10月02日 21:35，zwgogogo 写道： 谢谢，可以了 在2020年09月29日 11:11，ske1996 写道： 清空一遍nvram — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 请问怎么解决的，我这弄不好 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

ok啦，谢谢
