### ISSUE TITLE
Mate13 2020 i5触屏款安装成功，一些小tips

### ISSUE THREAD

**Issue by zy21802** [ske1996/matebook-13-2019-oc-efi#69]
1. 使用clover安装不成功。左边插口内核崩溃（禁行标志），右边插口memory panic。用的是楼主给的对应文件夹里的含OC的EFI。
2. 有些电脑默认EFI分区只有101MB，这样在AFPS抹盘就会空间不足报错。需要增加到200以上，我是300。
3. OC安装过程可以b站搜。
4. OC安装右边插口一开始依旧panic。左边才行。后面第二步又pannic，又换成了右边。
5. EasyUEFI里浏览文件要选择OpenCore.efi。
6. 一定确保电量充足。（省的报错换口电不够）

**Comment by ske1996** [comment]
关于第一个，我在那个安装的说明写了，删除两个与usb相关的驱动就行

关于你用oc也会panic推测与你的扩展坞有关，因为里面包含usb定制用的ssdt，有可能你的扩展坞与我用的有极大的不同，从而导致的这个问题
你安装时删除oc/acpi/uiac.aml应该就不会panic了
