### ISSUE TITLE
睡眠唤醒失败

### ISSUE THREAD

**Issue by Rex0519** [ske1996/matebook-13-2019-oc-efi#70]
大佬你好，我的机器是mb13 2019，系统10.15. 全部安装完成后其他一切正常，就是发现盒盖睡眠之后，开盖就不能恢复了，直接重启了，而且重启oc进mac还要再重新再显示一次huawei logo，才会进行oc跑码，进系统之后显示有system sleep wake的系统错误。请大佬麻烦看下，应该是我的个例。

Sleep Wake failure in EFI

Failure code:: 0xffffffff 0x002a001f

Please IGNORE the below stackshot

================================================================
Date/Time:        2020-09-27 15:05:53 +0200
OS Version:       ??? ??? (Build ???)
Architecture:     x86_64
Report Version:   29

Data Source:      Stackshots
Shared Cache:     0x29c6000 A6084965-AF6C-3445-96C1-29555469AF29

Event:            Sleep Wake Failure
Duration:         0.00s
Steps:            1

Boot args:        -v debug=0x100 keepsyms=1 chunklist-security-epoch=0 -chunklist-no-rev2-dev

Time Awake Since Boot: 22s

Process:          swd [276]
Architecture:     x86_64
Footprint:        460 KB
Start time:       2020-09-27 15:05:53 +0200
End time:         2020-09-27 15:05:53 +0200
Num samples:      1 (1)

  Thread 0x809    1 sample (1)    priority 4 (base 4)
  <thread QoS background (requested background), thread darwinbg, process darwinbg, IO tier 2>
  1  start + 1 (libdyld.dylib + 109769) [0x7fff69babcc9] 1
    1  ??? [0x1033f9454] 1
      1  ??? [0x1033f91dd] 1
        1  __stack_snapshot_with_config + 10 (libsystem_kernel.dylib + 135862) [0x7fff69d0d2b6] 1
         *1  ??? [0xffffff80002c1206] 1
           *1  ??? [0xffffff8000984c37] 1
             *1  ??? [0xffffff800089d7c1] 1
               *1  ??? [0xffffff80002e49e7] (running) 1

  Binary Images:
        0x7fff69b91000 -     0x7fff69bc7fff  libdyld.dylib (750.6)               <789A18C2-8AC7-3C88-813D-CD674376585D>  /usr/lib/system/libdyld.dylib
        0x7fff69cec000 -     0x7fff69d18fff  libsystem_kernel.dylib (6153.141.1) <2B6311E6-6240-3EF7-8C87-475B66F7452C>  /usr/lib/system/libsystem_kernel.dylib
Model: MacBookPro15,2, BootROM 1554.40.9.0.0, 4 processors, Quad-Core Intel Core i5, 1.8 GHz, 8 GB, SMC 
Graphics: kHW_IntelIrisGraphics655Item, Intel Iris Plus Graphics 655, spdisplays_builtin
Memory Module: BANK 0/ChannelA-DIMM0, 4 GB, LPDDR3, 2133 MHz, Samsung, -
Memory Module: BANK 2/ChannelB-DIMM0, 4 GB, LPDDR3, 2133 MHz, Samsung, -
AirPort: spairport_wireless_card_type_airport_extreme (0x8086, 0x2034), itlwm: 1.1.0 fw: 34.3125811985.0
Bluetooth: Version 7.0.6f7, 3 services, 26 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en2
PCI Card: Intel Iris Plus Graphics 655, VGA compatible controller, Internal@0,2,0
PCI Card: ALC256, Audio device, Built in
USB Device: USB 3.1 Bus
USB Device: 4-Port USB 3.0 Hub
USB Device: Bluetooth HCI
USB Device: HD Camera
USB Device: 4-Port USB 2.0 Hub
Thunderbolt Bus:

**Comment by Rex0519** [comment]
短时间之内睡眠没问题，能正常唤醒，但是长时间，比如放一晚或以上就会出现上述问题。

**Comment by ske1996** [comment]
解锁下cfg，重新定制下usb，具体的自己百度

**Comment by ske1996** [comment]
还有设置里的硬盘睡眠不要开启，还有就是禁止休眠，你可以都试一遍，具体的自己百度
