### ISSUE TITLE
有触控板问题的进来聊一下具体情况

### ISSUE THREAD

**Issue by ske1996** [ske1996/matebook-13-2019-oc-efi#73]
Report问题格式为:matebook 13(14)20xx,系统版本,EFI使用版本(比如0926)

然后说一下设置/触控板里有没有出来触控板的设置以及演示什么的，还有就是触控板有问题的具体表现

⚠️不按格式提出的直接删除处理

反馈前确认已经按照以下操作:
尝试激活fn后+f10至f12或者不激活的情况下按一下，每按一次划拉一下触控板

或者是
https://github.com/ske1996/matebook-13-2019-oc-efi/issues/45

**Comment by 894722197** [comment]
matebook13 
2019，10.15.7  0926
确认已经按照操作了。0814，可以使用触控板，WiFi 显示什么未插好之类的。
使用0916的配置文件，一切就都ok了，丝滑体验。

**Comment by hesongtao96** [comment]
间歇性问题，感觉有可能是win10+macos双系统的原因？只要是从win10重启进macOS就会出现无法触控的问题，F10-F12方法无效

**Comment by ske1996** [comment]
> matebook13 
> 
> 2019，10.15.7  0926
> 
> 确认已经按照操作了。0814，可以使用触控板，WiFi 显示什么未插好之类的。
> 
> 使用0918的配置文件，一切就都ok了，丝滑体验。

0814之后我删除了两个ssdt，一个是tpd0一个是gpi0，你有触控板问题可以把这两个ssdt复制进最新的oc/acpi后，修改config添加这两个进去

**Comment by AFK9527** [comment]
Matebook 14
2020，i5 10210U，10.15.7 尝试了0918和0926
现象：进入系统登录界面时，触摸板可用，填写密码进行系统登录后，触摸板开始无法使用，期间移除或者插入外置鼠标均没有改变，设置里面可以看到触摸板已经成功驱动

**Comment by ske1996** [comment]
> Matebook 14
> 
> 2020，i5 10210U，10.15.7 尝试了0918和0926
> 
> 现象：进入系统登录界面时，触摸板可用，填写密码进行系统登录后，触摸板开始无法使用，期间移除或者插入外置鼠标均没有改变，设置里面可以看到触摸板已经成功驱动



F11的那个有做吗，重置nvram有做吗

**Comment by AFK9527** [comment]
> > Matebook 14
> > 2020，i5 10210U，10.15.7 尝试了0918和0926
> > 现象：进入系统登录界面时，触摸板可用，填写密码进行系统登录后，触摸板开始无法使用，期间移除或者插入外置鼠标均没有改变，设置里面可以看到触摸板已经成功驱动
> 
> F11的那个有做吗，重置nvram有做吗

NVRAM尝试了，没有效果，晚点试试F11看看再过来回复一次

**Comment by AFK9527** [comment]
> > Matebook 14
> > 2020，i5 10210U，10.15.7 尝试了0918和0926
> > 现象：进入系统登录界面时，触摸板可用，填写密码进行系统登录后，触摸板开始无法使用，期间移除或者插入外置鼠标均没有改变，设置里面可以看到触摸板已经成功驱动
> 
> F11的那个有做吗，重置nvram有做吗

大神，刚试了充值NVRAM和F11，都无法解决登陆界面触摸板可用，登陆后无法使用的问题，但是发现屏幕的触摸功能可用？有没有可能是触摸板和触摸屏的驱动有冲突？ps0926和0918都尝试过了

**Comment by AFK9527** [comment]
![image](https://user-images.githubusercontent.com/73459271/97177640-6b41a500-17d1-11eb-9808-f3ac204783ae.png)
驱动效果如图

**Comment by ske1996** [comment]
> ![image](https://user-images.githubusercontent.com/73459271/97177640-6b41a500-17d1-11eb-9808-f3ac204783ae.png)
> 
> 驱动效果如图

别说，还真听过这么回事，具体咋屏蔽触屏我给忘了……

**Comment by AFK9527** [comment]
> > ![image](https://user-images.githubusercontent.com/73459271/97177640-6b41a500-17d1-11eb-9808-f3ac204783ae.png)
> > 驱动效果如图
> 
> 别说，还真听过这么回事，具体咋屏蔽触屏我给忘了……你要是找到了什么麻烦告诉我一下哈

在驱维护驱动github看到这段话，你研究一下
链接：https://github.com/acidanthera/VoodooPS2
This kext supports disabling touch input by pressing the Printscreen key on your keyboard, or the touchpad disable key on many laptops. Simply press the key to toggle touchpad input off and again to toggle it back on.

In addition, for 2-in-1 systems that do not support disabling the keyboard in hardware while in tablet mode you may toggle keyboard input off and on by holding option(Windows) and pressing the Printscreen key. Repeat the keypress to re-enable keyboard input. These settings are runtime only and do not persist across a reboot.

**Comment by ske1996** [comment]
> > > ![image](https://user-images.githubusercontent.com/73459271/97177640-6b41a500-17d1-11eb-9808-f3ac204783ae.png)
> 
> > > 驱动效果如图
> 
> > 
> 
> > 别说，还真听过这么回事，具体咋屏蔽触屏我给忘了……你要是找到了什么麻烦告诉我一下哈
> 
> 
> 
> 在驱维护驱动github看到这段话，你研究一下
> 
> 链接：https://github.com/acidanthera/VoodooPS2
> 
> This kext supports disabling touch input by pressing the Printscreen key on your keyboard, or the touchpad disable key on many laptops. Simply press the key to toggle touchpad input off and again to toggle it back on.
> 
> 
> 
> In addition, for 2-in-1 systems that do not support disabling the keyboard in hardware while in tablet mode you may toggle keyboard input off and on by holding option(Windows) and pressing the Printscreen key. Repeat the keypress to re-enable keyboard input. These settings are runtime only and do not persist across a reboot.
> 
> 
> 
> 

这不写的清清楚楚是触控板如何暂时关闭吗，跟触屏有啥关系

**Comment by AFK9527** [comment]
> > ![image](https://user-images.githubusercontent.com/73459271/97177640-6b41a500-17d1-11eb-9808-f3ac204783ae.png)
> > 驱动效果如图
> 
> 别说，还真听过这么回事，具体咋屏蔽触屏我给忘了……你要是找到了什么麻烦告诉我一下哈

搞定，终端输入 sudo kextcache -i\，然后按F10/F12，原因可能是我更换EFI，触摸板缓存没有重置吧，不过这个改善是在Big sur上完成的，catalina没有尝试

**Comment by Bearshineliu** [comment]
matebook13
2019，10.15.7 0926
左键点击实际效果是右键 蓝牙鼠标和USB鼠标均是，但点击顶部状态栏确没问题.. 重启后没问题，复现2次

**Comment by ske1996** [comment]
> matebook13
> 
> 2019，10.15.7 0926
> 
> 左键点击实际效果是右键 蓝牙鼠标和USB鼠标均是，但点击顶部状态栏确没问题.. 重启后没问题，复现2次


真头一次遇到这个，升级一下i2c全家桶，然后清空一下nvram试试吧
