### ISSUE TITLE
提问：蓝牙无法驱动。特殊机型：RedmiBook13，2019款

### ISSUE THREAD

**Issue by AndrewBaca** [ske1996/matebook-13-2019-oc-efi#75]
机型：RedmiBook13，2019款，i7-10510，8G，512G，正常运行。在此感谢ske1996大神的EFI。
Intel AC-9460，正常运行；
Intel 蓝牙无法使用，应该是没有驱动成功，因为log也出不来。

        最开始用的MoZyo大神的EFI，在10.15下正常，当时的蓝牙就偶尔有问题，选择一个特定机型MBP15.2，控制面板才会出现蓝牙选项，别的机型都不出现，也就无法使用蓝牙。MoZyo大神的EFI多个月未更新，无法适配big sur。

        在pcbeta提问，经ske1996大神讲解，用这里的EFI更换MoZyo的ACPI后，可以成功运行big sur，特此感谢。
        基本正常使用，两个小问题：1.唤醒偶尔崩溃并自动重启，2.只能引导big sur，无法安装big sur。
        因为这里的EFI不是专为我的机型适配的，所以能正常使用就已经十分感谢了🙏，再次感谢大佬@ske1996。

        但是蓝牙彻底消失了，不知道如何解决，最近几个EFI都更新了，也未解决蓝牙问题。因为一直用的蓝牙音箱和键盘，蓝牙功能确实很重要，大神能否提供下解决方案？
        再次感谢！

**Comment by ske1996** [comment]
删除oc/kext/airportitlwm以及编辑config删除掉里面的kernel/add里面的同名选项，然后更换itlwm+heliport的方案

**Comment by AndrewBaca** [comment]
> 删除oc/kext/airportitlwm以及编辑config删除掉里面的kernel/add里面的同名选项，然后更换itlwm+heliport的方案

刚刚已操作，问题依旧。打开蓝牙设置会提示 “您无法打开“蓝牙”偏好设置面板，因为该面板此时不可用。”
已确认，kext里面有intel bluetooth的驱动，config里相应的选项是选中启用的。也是很无奈，应该是无法驱动，在win下可以正常使用蓝牙，所以不是硬件问题。
![image](https://user-images.githubusercontent.com/58129211/95819351-618f5a80-0d58-11eb-97fc-daae1619db36.png)

**Comment by ske1996** [comment]
试试清空一下nvram，然后实在不行的话就考虑一下重新定制usb

**Comment by AndrewBaca** [comment]
> 试试清空一下nvram，然后实在不行的话就考虑一下重新定制usb

已尝试清空nvram，无效。
尝试定制usb。
小白百度中，再次感谢！

**Comment by AndrewBaca** [comment]
简单重新定制了USB，但问题依旧……
太复杂的定制USB不太会，没办法。
感谢大神的时间，后期有机会再研究研究，望早日解决！

**Comment by ske1996** [comment]
好像半年前听他跟我说过这个问题，他怀疑是10代u的锅，具体的我忘了，但是最后是折腾好了

**Comment by ske1996** [comment]
https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake-plus.html


你可以按照这个教程重新捋一遍看看
