### ISSUE TITLE
卡在（got stuck at）package no native mechanism 

### ISSUE THREAD

**Issue by mrdei** [ske1996/matebook-13-2019-oc-efi#77]
![WhatsApp Image 2020-10-14 at 02 47 21](https://user-images.githubusercontent.com/72679718/95959427-0bf29680-0dc8-11eb-9b14-a25452734347.jpeg)

![InkedWhatsApp Image 2020-10-14 at 02 47 21 (1)_LI](https://user-images.githubusercontent.com/72679718/95959452-1745c200-0dc8-11eb-90ae-2511ec325142.jpg)

![WhatsApp Image 2020-10-14 at 02 49 20](https://user-images.githubusercontent.com/72679718/95959472-20369380-0dc8-11eb-9d50-de4d1cf72787.jpeg)

**Comment by ske1996** [comment]
sorry,i'vent encounter a issue like that,maybe you should redownload image file of macos,or google that code for searching help

**Comment by ske1996** [comment]
wait,is your ssd pm981 from samsung?

**Comment by ske1996** [comment]
I dont understand what you said at frist,could you wrote it in english？

**Comment by mrdei** [comment]
> wait,is your ssd pm981 from samsung?

i changed it for ssd HP ex900 1TB

**Comment by ske1996** [comment]
Maybe what i say is not right,i think you should do 3 thing,redownload dmg,check esp partition if it over than 200MB(actully i recommand set it to over 500m),format the partition which you want to install macos to apfs for 2 times,not all container,just one partition of your ssd

**Comment by ske1996** [comment]
And when you got that issue,what efi did you use？

**Comment by mrdei** [comment]
![72AD7017-1631-4206-810C-C3962A444CA2](https://user-images.githubusercontent.com/72679718/96962562-b192bd80-14cc-11eb-9926-6736e6734295.jpeg)
Solved thanks
