### ISSUE TITLE
关于dvmt

### ISSUE THREAD

**Issue by pzw1999** [ske1996/matebook-13-2019-oc-efi#79]
作者你好，前段时间刚刚进行了dvmt的修改，鄙人查询到的dvmt偏移地址是0x107，偏移地址库是varstore，与教程中的不太一样，望指点迷津。鄙人机型matebook13-i3-2019款

**Comment by ske1996** [comment]
107，108都是

**Comment by pzw1999** [comment]
地址库是SaSetup还是CpuSetup呢？偏移地址107应该是10行7列吧？

**Comment by ske1996** [comment]
我写的清清楚楚的，你要是不相信我，你就按你自己想的去改，出事了别找我就行了

**Comment by pzw1999** [comment]
不是不信任，我只是想搞懂是怎么找到偏移地址库的，华为bios提取以后并没有给出地址库的偏移量，所以很头疼，希望你不要生气，望告知

**Comment by ske1996** [comment]
提出来之后直接command+f搜dvmt出来的两个，一个107，一个108
