### ISSUE TITLE
oc引导进不了windows

### ISSUE THREAD

**Issue by GJTNB** [ske1996/matebook-13-2019-oc-efi#80]
oc引导选择windows进不去，按F12可以进去windows，请问这个问题可以解决吗？

**Comment by ske1996** [comment]
这个不叫问题，是我故意为之，具体原因自己百度，也可以让你oc引导windows，具体的自己百度，不过你可能损失上千块的许可证

**Comment by GJTNB** [comment]
好的，谢谢大佬
