### ISSUE TITLE
【solved】About BigSur DB10,here is what you need to do

### ISSUE THREAD

**Issue by hinough** [ske1996/matebook-13-2019-oc-efi#82]
After the installation is done (I assume it is since it goes from Mac OS install to just Mac OS in OC boot menu) I get a kernel panic on boot. Adding a picture of the error I get. 
I have the Matebook 13 WRT-W19 (Which is the 2018 or 2019, unsure which one it is) with the latest EFI folder for Matebok 13 2018-2019 for Big Sur downloaded from [here](https://github.com/ske1996/matebook-13-2019-oc-efi/blob/master/matebook%2013%2614%202018-2019/20200918%20BigSur.7z)

![IMG_0040 1](https://user-images.githubusercontent.com/15803035/96386089-850f3680-1198-11eb-99e2-4a3fe8c77657.JPG)

**Comment by ske1996** [comment]
What is your macos version？ Is it Bigsur develop beta 10？

**Comment by hinough** [comment]
Ah yes forgot to add that, yes its the latest version available on the developer branch. So Im assuming that would be Beta 10

**Comment by ske1996** [comment]
You need to upgrade your opencore file to 0.6.2 and change misc/security/securymode to "Disabled"

P.s. It is 0.6.1 in my lastest release
