### ISSUE TITLE
无法从OC进入Windows

### ISSUE THREAD

**Issue by 2072219876** [ske1996/matebook-13-2019-oc-efi#83]
![16030801596093703682415130861549](https://user-images.githubusercontent.com/73091522/96400387-27fc9a80-1203-11eb-86fc-cfdbaa565845.jpg)
matebook14 i7 2020版
从OC进入Windows可看见图标，但是大约一秒后直接重启进efi，三次之后出现以上界面，请求大佬帮助

**Comment by ske1996** [comment]
去仔细阅读，安装后的说明，以及我所有的issue，我有说这个事
