### ISSUE TITLE
只安装了黑苹果，想要解锁CFG，应该怎么更新bios呢

### ISSUE THREAD

**Issue by LawrenceZhang** [ske1996/matebook-13-2019-oc-efi#85]
百度了一下，说要使用华为助手更新驱动，可是我现在电脑里只有黑苹果系统，咋整？
是需要换硬盘安装windows才可以吗？

**Comment by ske1996** [comment]
1.首先，我是建议去官网下载bios更新包的形式更新

2. linux下倒是可以用提取的bios的核心包（.bin）去更新，但是具体如何操作我没弄过，所以我不知道

**Comment by nukemiko** [comment]
可以找个装了PE系统的U盘安装官网下载的更新包
