### ISSUE TITLE
bios损坏

### ISSUE THREAD

**Issue by 7k7k163** [ske1996/matebook-13-2019-oc-efi#86]
可能是我的操作问题，现在bios损坏开机黑屏，应该怎么修复？

**Comment by ske1996** [comment]
给个视频啥的看看那，你弄什么了就损坏了？

**Comment by 7k7k163** [comment]
是这样，我的本子不是matebook，我按照知乎的一个帖子改的，大概思路是和这个一样，可能改错位置了，现状开机只有键盘灯亮，屏幕没反应，大概率是bios损坏，然后他建议我过来问问。
视频怎么给？

**Comment by ske1996** [comment]
那我就不好说了，建议去售后吧

**Comment by 7k7k163** [comment]
好的   感谢
