### ISSUE TITLE
关于图形化引导界面与开机音效

### ISSUE THREAD

**Issue by pzw1999** [ske1996/matebook-13-2019-oc-efi#87]
Matebook 13 2019  
CPU:i3
RAM:8g
SSD:东芝rc500

Works fine:一切很好，搞了半天图形化引导界面和开机音效，开机音效可以正常，图形化引导界面总是失败，期待大佬的下一个版本可以给出一个自带图形化界面的引导文件（引导会很大）
[手动狗头]
Doesnt work:

**Comment by ske1996** [comment]
不会做的
 
1.你肯定没看我写的安装后的注意事项
2.你想用oc的图形界面说明了你想通过oc切换os,这是我强烈反对的，因为oc会对所有通过oc引导的系统注入uuid和串号，因此你的其他正版系统的许可证以及其他的正版软件许可证会收到波及从而失效

综上所述，使用原生的uefi bootloader去boot windows，然后用oc去boot macos是最佳选择

所以按我所说，通过ctrl以及enter去选定macos为默认的oc引导os后直接在config关闭showpicker为最佳，根本不需要去看选择os的页面
