### ISSUE TITLE
Code中的【安装用clover的EFI】疑似损坏

### ISSUE THREAD

**Issue by X-Hello** [ske1996/matebook-13-2019-oc-efi#89]
按照下面的视频教程和注意事项，上面Code里的【安装用clover的EFI】下载后使用Bandzip无法打开提示未知压缩格式，而后使用DiskGenius检查发现提示【文件头数据与类型不匹配】，小白不是很懂，还请大佬帮忙解决

**Comment by ske1996** [comment]
不可能的，我前几天还下载用来着，你重新下一下，可能是你的下载损坏了，7z是一个很常见的压缩格式，自己去百度解压软件

**Comment by X-Hello** [comment]
emmmmm,我下载了两遍，都是一样的，我去下个7z试试

**Comment by X-Hello** [comment]
![image](https://user-images.githubusercontent.com/53436891/97776007-f8a14280-1b9f-11eb-8343-ca60ea935c9c.png)
您好，7z官方软件也打不开

**Comment by ske1996** [comment]
> ![image](https://user-images.githubusercontent.com/53436891/97776007-f8a14280-1b9f-11eb-8343-ca60ea935c9c.png)
> 
> 您好，7z官方软件也打不开

那反正我能打得开，你就多试试几个别的软件吧
