### ISSUE TITLE
macOS安装抹掉磁盘时显示未知错误：-110

### ISSUE THREAD

**Issue by X-Hello** [ske1996/matebook-13-2019-oc-efi#91]
机型：MateBook14 2019 硬盘西数512G
显卡MX250和GHP630
U盘金士顿32GB USB3.0
安装时显示错误代码-110，硬盘是是西数的，应该没有问题
另外想请教一下，安装时需要网络而目前网卡还没有驱动该怎么办呢，EFI使用的是库中的【安装用clover】

**Comment by X-Hello** [comment]
补图：
![Uploading 6D848460-F20B-47F1-90CE-66F365139036.jpeg…]()

**Comment by X-Hello** [comment]
补图：
![DD0C9EEA-03C7-4CBC-BBC1-82F355A873ED](https://user-images.githubusercontent.com/53436891/97798847-e63d0c80-1c64-11eb-8dd5-6cac9851d484.jpeg)

**Comment by X-Hello** [comment]
补图：
![140B0217-195F-46B4-9756-88BB67022348](https://user-images.githubusercontent.com/53436891/97798868-0d93d980-1c65-11eb-9766-caf9e2d903ae.jpeg)

**Comment by ske1996** [comment]
第一，我给的视频教程以及我写的镜像下载里是说的准备完整的系统镜像，因此不存在安装时联网问题，是你自己的问题

第二，那个错误我没遇到过，自己百度下错误代码吧

**Comment by X-Hello** [comment]
> 首先，我给的视频教程以及我写的补充下载里是说的准备完整的系统交换机，因此不存在安装时联网问题，是你自己的问题
> 
> 第二，那个错误我没遇到过，自己百度下错误代码吧

如果百度有用我就不会来问了……镜像是黑果小兵下的，我自己排除下问题吧

**Comment by ske1996** [comment]
你百分百的按照教程循规蹈矩不会出现你的问题
