### ISSUE TITLE
随航和airdrop不能用

### ISSUE THREAD

**Issue by zy21802** [ske1996/matebook-13-2019-oc-efi#93]
mate13 2020 i5，连接wifi，随航咋都是超时，airdrop能被ipad搜索到但是它自己没法搜到ipad，ipad发送文件过去一直是“正在等待”。另外airpods连不上呀？

**Comment by lioneliio** [comment]
想要使用原生的接力、随航、隔空投递…… 需要把网卡替换为白苹果网卡。

**Comment by ske1996** [comment]
随航连线用，handoff可以用，airdrop不能用

我什么时候说了airdrop可以用了？

另外你airpods的问题，你在电脑上做配对了吗？你确定你用对了airpods？
