### ISSUE TITLE
【Beta 11.0.1】Freeze when i try to boot

### ISSUE THREAD

**Issue by claudiuh** [ske1996/matebook-13-2019-oc-efi#94]
Hey, i managed to install Big Sur with your efi in Matebook 14 but wjen i try to boot the system it just stops here:
![16044377702824760401457489476063](https://user-images.githubusercontent.com/8824900/98040853-ea119000-1e18-11eb-8e5e-20e2c5c02efb.jpg)

Do you have any ideia what's wrong?

**Comment by ske1996** [comment]
1. What is the os version？
2. Which efi you used,be specifically

**Comment by claudiuh** [comment]
1. Big Sur Beta 11.0.1
2. matebook14.2020.bigsur.0926.7z
3. I5-10210U
4. Western Digital (WDC PC SN730 SDBPNTY-512G-1027) SSD

Sorry i didn't notice. I didn't change anything in your efi.

**Comment by ske1996** [comment]
> 1. Big Sur Beta 11.0.1
> 
> 2. matebook14.2020.bigsur.0926.7z
> 
> 3. I5-10210U
> 
> 4. Western Digital (WDC PC SN730 SDBPNTY-512G-1027) SSD
> 
> 
> 
> Sorry i didn't notice. I didn't change anything in your efi.

Okay,i recommand you to do 2 thing:

1. Upgrade OpenCore to 0.6.3
2. switch airportitlwm.kext which is in efi/oc/kext to itlwm.kext and edit config.plist to record that switch

3. Or dont do that two things,switch you image to older than 11.0 DB9 or any version of catalina
