### ISSUE TITLE
关于如何开启sip(说实话这个东西太基础…一百度就出来的)

### ISSUE THREAD

**Issue by Amaster9** [ske1996/matebook-13-2019-oc-efi#95]
![16045532882008697850926179361876](https://user-images.githubusercontent.com/73091522/98200620-ebea6900-1f68-11eb-9293-949e0637cd9f.jpg)
如图，使用命令csrutil disable后状态任然未知，重启之后SIP仍处于开启状态

**Comment by ske1996** [comment]
csr-active-config改成八个0，具体的自己百度oc sip
