### ISSUE TITLE
想问问大家这个问题是咋解决的““以太网”有一个自分配的IP地址，将无法接入互联网。”

### ISSUE THREAD

**Issue by Serendipity-Y** [ske1996/matebook-13-2019-oc-efi#97]

**Comment by Serendipity-Y** [comment]
Wi-Fi使用无任何问题，因为学校校园网带宽太小 路由器也比较渣 所以我想在宿舍的时候插网线稳定一点  但是我插上网线就这个样子 百度了很久 也没找到 解决办法！ 跪求大佬们给个主意 谢谢了！！🙏🙏🙏

**Comment by ske1996** [comment]
一没图，二没日志，我给你算一卦？

**Comment by Serendipity-Y** [comment]
![529BCCB0-4417-4EB6-9A8F-E2FF243DA8F9](https://user-images.githubusercontent.com/56247607/98239101-671c4100-1fa2-11eb-8f72-c2202e9f954a.png)

**Comment by ske1996** [comment]
不是连上了吗

**Comment by Serendipity-Y** [comment]
大佬实在不好意思 我不太会github的操作  特意注册的账号上来问的   以太网连接dhcp地址分配失败  我想的是 不连接Wi-Fi 直接用网线连接使用 我的电脑型号是 8265u mx150

**Comment by Serendipity-Y** [comment]
大佬我用的是绿联拓展坞  刚刚问卖家安装了驱动 我试过新建接口  网上说是新建一个usb的pppoe拨号模式 但是我新建了 发现没有新建的pppoe拨号模式无usb这个选项  我们学校是通过宽带拨号模式 我在路由器上做了拨号设置 通过路由器直接接了一根网线到电脑

**Comment by Serendipity-Y** [comment]
实在不好意思  我是个刚接触黑苹果的小白 打扰到您 万分抱歉

**Comment by ske1996** [comment]
我倒不觉得你打扰，你一开始啥也没说，这没法看问题

**Comment by ske1996** [comment]
先说一下关于网线的问题，虽不是我本人，但也算是亲眼所见，mb13的19款，绿联那个300块左右的扩展坞，也没做什么，怼上网线也就用了，我觉得要么你就看看重新定制usb，要么你就学一下关于网络接口相关的知识，然后看看问题，毕竟我啥也没看见，也说不了啥，按我的思路自己百度搜搜折腾下吧

**Comment by Serendipity-Y** [comment]
好的 我去折腾折腾 感谢回复  万分感激 🙏
