### ISSUE TITLE
MateBook14 2019 10.15.7版本 设置/网络中无wifi接口 网卡型号Intel AC 9560

### ISSUE THREAD

**Issue by groveswallow** [ske1996/matebook-13-2019-oc-efi#98]
非常感谢作者的无私分享，我按照官方的最新教程以及Sanity Checker的对照，多次尝试后仍然卡在识别trackpads无法进入图形安装程序（还好有巨佬的EFI，拯救了萌新）。
情况以及问题：
OC引导，同时U盘制作也为OC官方的工具gibMacOS，制作的系统为10.15.3，EFI为大佬的20200918 Catalina.7z。
进入安装程序后为在线安装，要求必须联网，此时无线网卡有效。
在安装过程中自动给装成了10.15.7（在台式机上未出现该问题），安装完毕能正常进入系统。
但是无线网卡（Intel AC 9560）失效（暂未发现其他的严重问题），请问是因为系统10.15.7造成的结果吗？是否需要版本回退重新安装？
谢谢！

**Comment by ske1996** [comment]
1.为什么不按我的格式提交？
2.配个设置-网络里的图，给我看看接口情况

**Comment by groveswallow** [comment]
> 1.为什么不按我的格式提交？
> 2.配个设置-网络里的图，给我看看接口情况

抱歉。
图如下：
![f1cada3bf315fbf8ba97e710dccfc49](https://user-images.githubusercontent.com/27988112/98330037-895e9f00-2034-11eb-91c5-b75129bb9caa.jpg)
![1b8763d93800758bf8367d6c2ba8b22](https://user-images.githubusercontent.com/27988112/98330042-8cf22600-2034-11eb-9bd9-693962da554d.jpg)
谢谢大佬。

**Comment by ske1996** [comment]
1.左下角加号按一下看看会不会出来wifi的接口
2.换成0926的efi
3.reset一下nvram

试试

问题是接口没出来

**Comment by groveswallow** [comment]
> 1.左下角加号按一下看看会不会出来wifi的接口，或者删除网络里的所有接口，应用，重启，然后重新添加接口
> 2.换成0926的efi
> 3.reset一下nvram
> 4.以上动作完成后还是没出来的话就去更新airportitlwm至最新的1.2 alpha，然后重复以上三点
> 
> 5.如果还是不行就切换到itlwm+heliport的方案，itlwm与airportitlwm不可同时加载，并需要修改config去添加itlwm
> 
> 试试
> 
> 问题是接口没出来
> 
> 下次不按格式提交，没图没日志的将直接删除该issue

好的！
